using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
namespace LoanSystem.Modules.LoanOrigination.Infrastructure.Migrations;

[DbContext(typeof(LoanOriginationDbContext))]
[Migration("20260907040000_LoanOrigination_InspectionMortgagePrerequisites")]
public sealed class LoanOriginationInspectionMortgagePrerequisites : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.AddColumn<string>(name: "inspection_prerequisite_status", table: "loan_applications", schema: "loan_origination", type: "nvarchar(30)", maxLength: 30, nullable: false, defaultValue: "NotStarted");
        migrationBuilder.AddColumn<string>(name: "mortgage_status", table: "loan_applications", schema: "loan_origination", type: "nvarchar(30)", maxLength: 30, nullable: false, defaultValue: "NotStarted");
        migrationBuilder.AddColumn<string>(name: "mortgage_decision", table: "loan_applications", schema: "loan_origination", type: "nvarchar(max)", nullable: true);
        migrationBuilder.AddColumn<string>(name: "document_prerequisite_status", table: "loan_applications", schema: "loan_origination", type: "nvarchar(30)", maxLength: 30, nullable: false, defaultValue: "NotStarted");
        migrationBuilder.CreateTable(name: "property_inspections", schema: "loan_origination", columns: t => new { property_inspection_id = t.Column<Guid>("uniqueidentifier", nullable: false), loan_application_id = t.Column<Guid>("uniqueidentifier", nullable: false), inspector_id = t.Column<Guid>("uniqueidentifier", nullable: false), governorate = t.Column<string>("nvarchar(100)", maxLength: 100, nullable: false), state = t.Column<string>("nvarchar(100)", maxLength: 100, nullable: false), area = t.Column<string>("nvarchar(200)", maxLength: 200, nullable: false), number_of_floors = t.Column<int>("int", nullable: false), number_of_rooms = t.Column<int>("int", nullable: false), property_area = t.Column<decimal>("decimal(18,2)", nullable: false), property_condition = t.Column<string>("nvarchar(500)", maxLength: 500, nullable: false), inspection_date = t.Column<DateOnly>("date", nullable: true), result = t.Column<string>("nvarchar(500)", maxLength: 500, nullable: false), status = t.Column<string>("nvarchar(30)", maxLength: 30, nullable: false), notes = t.Column<string>("nvarchar(max)", nullable: true), created_at_utc = t.Column<DateTimeOffset>("datetimeoffset", nullable: false), updated_at_utc = t.Column<DateTimeOffset>("datetimeoffset", nullable: false), finalized_at_utc = t.Column<DateTimeOffset>("datetimeoffset", nullable: true), row_version = t.Column<byte[]>("rowversion", rowVersion: true, nullable: false) }, constraints: c => { c.PrimaryKey("PK_property_inspections", x => x.property_inspection_id); c.ForeignKey("FK_property_inspections_loan_applications", x => x.loan_application_id, "loan_applications", "loan_application_id", "loan_origination", onDelete: ReferentialAction.Restrict); });
        migrationBuilder.CreateIndex("IX_property_inspections_loan_application_id", "property_inspections", "loan_application_id", "loan_origination");
        migrationBuilder.CreateTable(name: "application_documents", schema: "loan_origination", columns: t => new { loan_application_id = t.Column<Guid>("uniqueidentifier", nullable: false), document_id = t.Column<Guid>("uniqueidentifier", nullable: false), document_type = t.Column<string>("nvarchar(30)", maxLength: 30, nullable: false), is_required = t.Column<bool>("bit", nullable: false), attached_at_utc = t.Column<DateTimeOffset>("datetimeoffset", nullable: false) }, constraints: c => { c.PrimaryKey("PK_application_documents", x => new { x.loan_application_id, x.document_id }); c.ForeignKey("FK_application_documents_loan_applications", x => x.loan_application_id, "loan_applications", "loan_application_id", "loan_origination", onDelete: ReferentialAction.Restrict); });
    }
    protected override void Down(MigrationBuilder migrationBuilder) { migrationBuilder.DropTable("application_documents", "loan_origination"); migrationBuilder.DropTable("property_inspections", "loan_origination"); migrationBuilder.DropColumn("inspection_prerequisite_status", "loan_applications", "loan_origination"); migrationBuilder.DropColumn("mortgage_status", "loan_applications", "loan_origination"); migrationBuilder.DropColumn("mortgage_decision", "loan_applications", "loan_origination"); migrationBuilder.DropColumn("document_prerequisite_status", "loan_applications", "loan_origination"); }
}
