using LoanSystem.Contracts;
using LoanSystem.Modules.LoanOrigination.Domain;
namespace LoanSystem.Modules.LoanOrigination.Application;

public static class LoanApplicationPermissions { public const string Read = "loanApplications.read", Create = "loanApplications.create", Update = "loanApplications.update", EvaluateEligibility = "loanApplications.evaluateEligibility", Submit = "loanApplications.submit"; }
public sealed record CreateLoanApplication(Guid BorrowerId, Guid LoanProductVersionId, decimal RequestedAmount, string FinancingType);
public sealed record EditLoanApplication(decimal RequestedAmount, string FinancingType);
public sealed record LoanApplicationDto(Guid LoanApplicationId, Guid BorrowerId, Guid LoanProductId, Guid LoanProductVersionId, decimal RequestedAmount, string Currency, string FinancingType, string Status, BorrowerSnapshot BorrowerSnapshot, ProductSnapshot ProductSnapshot, EligibilityDecision? EligibilityDecision, DateTimeOffset CreatedAtUtc, DateTimeOffset UpdatedAtUtc, DateTimeOffset? SubmittedAtUtc, string ETag);
public sealed record LoanApplicationListItem(Guid LoanApplicationId, Guid BorrowerId, string BorrowerName, Guid LoanProductId, string ProductName, decimal RequestedAmount, string Currency, string FinancingType, string Status, DateTimeOffset CreatedAtUtc);
public sealed record LoanApplicationSearch(Guid? LoanApplicationId, Guid? BorrowerId, Guid? LoanProductId, LoanApplicationStatus? Status, int PageNumber = 1, int PageSize = 25);
public sealed record LoanApplicationPage(IReadOnlyList<LoanApplicationListItem> Items, int PageNumber, int PageSize, int TotalCount);
public interface ILoanApplicationStore { Task AddAsync(LoanApplication value, CancellationToken ct); Task<LoanApplication?> FindAsync(Guid id, CancellationToken ct); Task<LoanApplicationPage> SearchAsync(LoanApplicationSearch search, CancellationToken ct); Task<int> CountConflictingApplicationsAsync(Guid borrowerId, Guid excludeApplicationId, CancellationToken ct); void Expect(LoanApplication value, byte[] expected); Task SaveAsync(CancellationToken ct); }
public sealed class LoanApplicationConcurrencyException : Exception;
public sealed class BorrowerUnavailableException(string code) : Exception(code) { public string Code { get; } = code; }
public sealed class ProductUnavailableException(string code) : Exception(code) { public string Code { get; } = code; }
public sealed class LoanApplicationService(ILoanApplicationStore store, IBorrowersModule borrowers, ILoanProductsModule products)
{
    public async Task<LoanApplicationDto> CreateAsync(CreateLoanApplication input, CancellationToken ct) { var b = await borrowers.GetAsync(input.BorrowerId, ct) ?? throw new BorrowerUnavailableException("loanApplications.borrowerNotFound"); if (!b.IsActive) throw new BorrowerUnavailableException("loanApplications.borrowerInactive"); var lookup = await products.GetVersionAsync(input.LoanProductVersionId, DateOnly.FromDateTime(DateTime.UtcNow), ct); if (lookup.Status != LoanProductVersionLookupStatus.Available || lookup.Version is null) throw new ProductUnavailableException(lookup.Status == LoanProductVersionLookupStatus.NotFound ? "loanApplications.productVersionNotFound" : "loanApplications.productVersionUnavailable"); var v = lookup.Version; var borrower = new BorrowerSnapshot(b.CivilNumber, b.EmployeeNumber, b.FullName, b.PhoneNumber, b.Nationality, b.Organization, b.RankGrade, b.EmploymentInformation, "Active"); var product = new ProductSnapshot(v.LoanProductId, v.LoanProductVersionId, v.ProductName, v.VersionNumber, v.MaximumAmount, v.Currency, v.DeductionPercentage, v.FinancingTypes.ToArray(), new(v.EligibilityConfiguration.RequiredNationality, v.EligibilityConfiguration.MaximumApplicationCount, v.EligibilityConfiguration.RankGradeAmountRules.Select(x => new ProductRankGradeRuleSnapshot(x.RankGrade, x.MaximumAmount)).ToArray(), v.EligibilityConfiguration.MaximumTermMonths, v.EligibilityConfiguration.DueDateRule), v.EffectiveFrom, v.EffectiveTo, v.ProductStatus, v.VersionStatus, v.PublishedAtUtc); var a = LoanApplication.Create(b.BorrowerId, product, input.RequestedAmount, input.FinancingType, borrower); await store.AddAsync(a, ct); await store.SaveAsync(ct); return Map(a); }
    public async Task<LoanApplicationDto?> GetAsync(Guid id, CancellationToken ct) { var a = await store.FindAsync(id, ct); return a is null ? null : Map(a); }
    public Task<LoanApplicationPage> SearchAsync(LoanApplicationSearch s, CancellationToken ct) => store.SearchAsync(s with { PageNumber = Math.Max(1, s.PageNumber), PageSize = Math.Clamp(s.PageSize, 1, 100) }, ct);
    public async Task<LoanApplicationDto?> EditAsync(Guid id, EditLoanApplication input, byte[] expected, CancellationToken ct) { var a = await store.FindAsync(id, ct); if (a is null) return null; a.EditDraft(input.RequestedAmount, input.FinancingType); store.Expect(a, expected); await store.SaveAsync(ct); return Map(a); }
    public async Task<LoanApplicationDto?> EvaluateEligibilityAsync(Guid id, byte[] expected, CancellationToken ct) { var a = await store.FindAsync(id, ct); if (a is null) return null; store.Expect(a, expected); var count = await store.CountConflictingApplicationsAsync(a.BorrowerId, a.Id, ct); a.EvaluateEligibility(count); await store.SaveAsync(ct); return Map(a); }
    public async Task<LoanApplicationDto?> SubmitAsync(Guid id, byte[] expected, CancellationToken ct) { var a = await store.FindAsync(id, ct); if (a is null) return null; store.Expect(a, expected); if (a.Status != LoanApplicationStatus.Draft) throw new LoanApplicationStateException(); if (a.EligibilityDecision is null) throw new EligibilityRequiredException(); var lookup = await products.GetVersionAsync(a.LoanProductVersionId, DateOnly.FromDateTime(DateTime.UtcNow), ct); if (lookup.Status != LoanProductVersionLookupStatus.Available) throw new ProductUnavailableException("loanApplications.productVersionUnavailable"); var count = await store.CountConflictingApplicationsAsync(a.BorrowerId, a.Id, ct); var decision = a.EvaluateEligibility(count); if (!decision.IsEligible) { await store.SaveAsync(ct); throw new LoanApplicationIneligibleException(); } a.Submit(); await store.SaveAsync(ct); return Map(a); }
    public static LoanApplicationDto Map(LoanApplication a) => new(a.Id, a.BorrowerId, a.LoanProductId, a.LoanProductVersionId, a.RequestedAmount, a.Currency, a.FinancingType, a.Status.ToString(), a.BorrowerSnapshot, a.ProductSnapshot, a.EligibilityDecision, a.CreatedAtUtc, a.UpdatedAtUtc, a.SubmittedAtUtc, Convert.ToBase64String(a.RowVersion));
}
