using LoanSystem.Contracts;
using LoanSystem.Modules.LoanOrigination.Domain;
namespace LoanSystem.Modules.LoanOrigination.Application;

public static class LoanApplicationPermissions { public const string Read = "loanApplications.read", Create = "loanApplications.create", Update = "loanApplications.update", EvaluateEligibility = "loanApplications.evaluateEligibility", Submit = "loanApplications.submit", UnitApprove = "loanApplications.unitApprove", CommitteeApprove = "loanApplications.committeeApprove", MortgageManage = "loanApplications.mortgageManage"; }
public static class InspectionPermissions { public const string Create = "inspections.create", Approve = "inspections.approve"; }
public sealed record CreateLoanApplication(Guid BorrowerId, Guid LoanProductVersionId, decimal RequestedAmount, string FinancingType);
public sealed record EditLoanApplication(decimal RequestedAmount, string FinancingType);
public sealed record UnitDecisionCommand(Guid ApplicationId, Guid ActorUserId, UnitDecision Decision, string? Comment, byte[] ExpectedRowVersion);
public sealed record CommitteeDecisionCommand(Guid ApplicationId, Guid ActorUserId, CommitteeDecision Decision, string? Comment, byte[] ExpectedRowVersion);
public sealed record ApplicationDocumentDto(Guid DocumentId, string DocumentType, bool IsRequired, DateTimeOffset AttachedAtUtc);
public sealed record LoanApplicationDto(Guid LoanApplicationId, Guid BorrowerId, Guid LoanProductId, Guid LoanProductVersionId, decimal RequestedAmount, string Currency, string FinancingType, string Status, BorrowerSnapshot BorrowerSnapshot, ProductSnapshot ProductSnapshot, EligibilityDecision? EligibilityDecision, DateTimeOffset CreatedAtUtc, DateTimeOffset UpdatedAtUtc, DateTimeOffset? SubmittedAtUtc, UnitApprovalDecision? UnitApproval, CommitteeApprovalDecision? CommitteeApproval, DateTimeOffset? RejectedAtUtc, string ETag, string InspectionPrerequisiteStatus, string MortgageStatus, MortgageDecision? MortgageDecision, string DocumentPrerequisiteStatus, IReadOnlyList<ApplicationDocumentDto> ApplicationDocuments);
public sealed record LoanApplicationListItem(Guid LoanApplicationId, Guid BorrowerId, string BorrowerName, Guid LoanProductId, string ProductName, decimal RequestedAmount, string Currency, string FinancingType, string Status, DateTimeOffset CreatedAtUtc, DateTimeOffset UpdatedAtUtc, DateTimeOffset? SubmittedAtUtc);
public sealed record LoanApplicationSearch(Guid? LoanApplicationId, Guid? BorrowerId, Guid? LoanProductId, LoanApplicationStatus? Status, int PageNumber = 1, int PageSize = 25);
public sealed record LoanApplicationPage(IReadOnlyList<LoanApplicationListItem> Items, int PageNumber, int PageSize, int TotalCount);
public interface ILoanApplicationStore { Task AddAsync(LoanApplication value, CancellationToken ct); Task<LoanApplication?> FindAsync(Guid id, CancellationToken ct); Task<LoanApplicationPage> SearchAsync(LoanApplicationSearch search, CancellationToken ct); Task<int> CountConflictingApplicationsAsync(Guid borrowerId, Guid excludeApplicationId, CancellationToken ct); void Expect(LoanApplication value, byte[] expected); Task SaveAsync(CancellationToken ct); }
public sealed class LoanApplicationConcurrencyException : Exception;
public sealed class BorrowerUnavailableException(string code) : Exception(code) { public string Code { get; } = code; }
public sealed class ProductUnavailableException(string code) : Exception(code) { public string Code { get; } = code; }
public sealed class LoanApplicationService(ILoanApplicationStore store, IBorrowersModule borrowers, ILoanProductsModule products, IDocumentsModule documents)
{
    public LoanApplicationService(ILoanApplicationStore store, IBorrowersModule borrowers, ILoanProductsModule products) : this(store, borrowers, products, new UnavailableDocumentsModule()) { }
    public async Task<LoanApplicationDto> CreateAsync(CreateLoanApplication input, CancellationToken ct) { var b = await borrowers.GetAsync(input.BorrowerId, ct) ?? throw new BorrowerUnavailableException("loanApplications.borrowerNotFound"); if (!b.IsActive) throw new BorrowerUnavailableException("loanApplications.borrowerInactive"); var lookup = await products.GetVersionAsync(input.LoanProductVersionId, DateOnly.FromDateTime(DateTime.UtcNow), ct); if (lookup.Status != LoanProductVersionLookupStatus.Available || lookup.Version is null) throw new ProductUnavailableException(lookup.Status == LoanProductVersionLookupStatus.NotFound ? "loanApplications.productVersionNotFound" : "loanApplications.productVersionUnavailable"); var v = lookup.Version; var borrower = new BorrowerSnapshot(b.CivilNumber, b.EmployeeNumber, b.FullName, b.PhoneNumber, b.Nationality, b.Organization, b.RankGrade, b.EmploymentInformation, "Active"); var product = new ProductSnapshot(v.LoanProductId, v.LoanProductVersionId, v.ProductName, v.VersionNumber, v.MaximumAmount, v.Currency, v.DeductionPercentage, v.FinancingTypes.ToArray(), new(v.EligibilityConfiguration.RequiredNationality, v.EligibilityConfiguration.MaximumApplicationCount, v.EligibilityConfiguration.RankGradeAmountRules.Select(x => new ProductRankGradeRuleSnapshot(x.RankGrade, x.MaximumAmount)).ToArray(), v.EligibilityConfiguration.MaximumTermMonths, v.EligibilityConfiguration.DueDateRule), v.EffectiveFrom, v.EffectiveTo, v.ProductStatus, v.VersionStatus, v.PublishedAtUtc); var a = LoanApplication.Create(b.BorrowerId, product, input.RequestedAmount, input.FinancingType, borrower); await store.AddAsync(a, ct); await store.SaveAsync(ct); return Map(a); }
    public async Task<LoanApplicationDto?> GetAsync(Guid id, CancellationToken ct) { var a = await store.FindAsync(id, ct); return a is null ? null : Map(a); }
    public Task<LoanApplicationPage> SearchAsync(LoanApplicationSearch s, CancellationToken ct) => store.SearchAsync(s with { PageNumber = Math.Max(1, s.PageNumber), PageSize = Math.Clamp(s.PageSize, 1, 100) }, ct);
    public async Task<LoanApplicationDto?> EditAsync(Guid id, EditLoanApplication input, byte[] expected, CancellationToken ct) { var a = await store.FindAsync(id, ct); if (a is null) return null; a.EditDraft(input.RequestedAmount, input.FinancingType); store.Expect(a, expected); await store.SaveAsync(ct); return Map(a); }
    public async Task<LoanApplicationDto?> EvaluateEligibilityAsync(Guid id, byte[] expected, CancellationToken ct) { var a = await store.FindAsync(id, ct); if (a is null) return null; store.Expect(a, expected); var count = await store.CountConflictingApplicationsAsync(a.BorrowerId, a.Id, ct); a.EvaluateEligibility(count); await store.SaveAsync(ct); return Map(a); }
    public async Task<LoanApplicationDto?> SubmitAsync(Guid id, byte[] expected, CancellationToken ct) { var a = await store.FindAsync(id, ct); if (a is null) return null; store.Expect(a, expected); if (a.Status != LoanApplicationStatus.Draft) throw new LoanApplicationStateException(); if (a.EligibilityDecision is null) throw new EligibilityRequiredException(); var lookup = await products.GetVersionAsync(a.LoanProductVersionId, DateOnly.FromDateTime(DateTime.UtcNow), ct); if (lookup.Status != LoanProductVersionLookupStatus.Available) throw new ProductUnavailableException("loanApplications.productVersionUnavailable"); var count = await store.CountConflictingApplicationsAsync(a.BorrowerId, a.Id, ct); var decision = a.EvaluateEligibility(count); if (!decision.IsEligible) { await store.SaveAsync(ct); throw new LoanApplicationIneligibleException(); } a.Submit(); await store.SaveAsync(ct); return Map(a); }
    public async Task<LoanApplicationDto?> DecideByUnitAsync(UnitDecisionCommand input, CancellationToken ct) { var a = await store.FindAsync(input.ApplicationId, ct); if (a is null) return null; store.Expect(a, input.ExpectedRowVersion); if (input.Decision == UnitDecision.Approved) a.ApproveByUnit(input.ActorUserId, input.Comment); else a.RejectByUnit(input.ActorUserId, input.Comment); await store.SaveAsync(ct); return Map(a); }
    public async Task<LoanApplicationDto?> DecideByCommitteeAsync(CommitteeDecisionCommand input, CancellationToken ct) { var a = await store.FindAsync(input.ApplicationId, ct); if (a is null) return null; store.Expect(a, input.ExpectedRowVersion); if (input.Decision == CommitteeDecision.Approved) a.ApproveByCommittee(input.ActorUserId, input.Comment); else a.RejectByCommittee(input.ActorUserId, input.Comment); await store.SaveAsync(ct); return Map(a); }
    public async Task<LoanApplicationDto?> AttachDocumentAsync(Guid id, Guid documentId, ApplicationDocumentType type, Guid actor, byte[] expected, CancellationToken ct) { var a = await store.FindAsync(id, ct); if (a is null) return null; store.Expect(a, expected); var available = await documents.GetAccessibleAsync(documentId, actor, ct); if (available is null || !available.IsActive) throw new DocumentUnavailableException(); a.AttachDocument(documentId, type); await store.SaveAsync(ct); return Map(a); }
    public async Task<LoanApplicationDto?> DetachDocumentAsync(Guid id, Guid documentId, byte[] expected, CancellationToken ct) { var a = await store.FindAsync(id, ct); if (a is null) return null; store.Expect(a, expected); a.DetachDocument(documentId); await store.SaveAsync(ct); return Map(a); }
    public async Task<LoanApplicationDto?> CompleteMortgageAsync(Guid id, Guid actor, string? comment, byte[] expected, CancellationToken ct) { var a = await store.FindAsync(id, ct); if (a is null) return null; store.Expect(a, expected); a.CompleteMortgage(actor, comment); await store.SaveAsync(ct); return Map(a); }
    public async Task<LoanApplicationDto?> WaiveMortgageAsync(Guid id, Guid actor, string? reason, string? comment, byte[] expected, CancellationToken ct) { var a = await store.FindAsync(id, ct); if (a is null) return null; store.Expect(a, expected); a.WaiveMortgage(actor, reason, comment); await store.SaveAsync(ct); return Map(a); }
    public static LoanApplicationDto Map(LoanApplication a) => new(a.Id, a.BorrowerId, a.LoanProductId, a.LoanProductVersionId, a.RequestedAmount, a.Currency, a.FinancingType, a.Status.ToString(), a.BorrowerSnapshot, a.ProductSnapshot, a.EligibilityDecision, a.CreatedAtUtc, a.UpdatedAtUtc, a.SubmittedAtUtc, a.UnitApproval, a.CommitteeApproval, a.RejectedAtUtc, Convert.ToBase64String(a.RowVersion), a.InspectionPrerequisiteStatus.ToString(), a.MortgageStatus.ToString(), a.MortgageDecision, a.DocumentPrerequisiteStatus.ToString(), a.ApplicationDocuments.Select(x => new ApplicationDocumentDto(x.DocumentId, x.DocumentType.ToString(), x.IsRequired, x.AttachedAtUtc)).ToArray());
}
public sealed class DocumentUnavailableException : Exception;
file sealed class UnavailableDocumentsModule : IDocumentsModule { public Task<DocumentReferenceContract?> GetAccessibleAsync(Guid documentId, Guid actorUserId, CancellationToken cancellationToken = default) => Task.FromResult<DocumentReferenceContract?>(null); }

public sealed record EditInspection(string Governorate, string State, string Area, int NumberOfFloors, int NumberOfRooms, decimal PropertyArea, string PropertyCondition, DateOnly? InspectionDate, string Result, string? Notes);
public sealed record PropertyInspectionDto(Guid PropertyInspectionId, Guid LoanApplicationId, Guid InspectorId, string Governorate, string State, string Area, int NumberOfFloors, int NumberOfRooms, decimal PropertyArea, string PropertyCondition, DateOnly? InspectionDate, string Result, string Status, string? Notes, DateTimeOffset CreatedAtUtc, DateTimeOffset UpdatedAtUtc, DateTimeOffset? FinalizedAtUtc, string ETag);
public interface IPropertyInspectionStore
{
    Task AddAsync(PropertyInspection inspection, CancellationToken ct); Task<PropertyInspection?> FindAsync(Guid id, CancellationToken ct); Task<IReadOnlyList<PropertyInspection>> FindByApplicationAsync(Guid applicationId, CancellationToken ct); void Expect(PropertyInspection inspection, byte[] expected); Task SaveAsync(CancellationToken ct);
}
public sealed class InspectionConcurrencyException : Exception;
public sealed class ReinspectionNotSupportedException : Exception;
public sealed class PropertyInspectionService(IPropertyInspectionStore inspections, ILoanApplicationStore applications)
{
    public async Task<PropertyInspectionDto?> CreateAsync(Guid applicationId, Guid inspectorId, byte[] expectedApplicationVersion, CancellationToken ct) { var app = await applications.FindAsync(applicationId, ct); if (app is null) return null; applications.Expect(app, expectedApplicationVersion); if ((await inspections.FindByApplicationAsync(applicationId, ct)).Count != 0) throw new ReinspectionNotSupportedException(); app.BeginPrerequisites(); var inspection = PropertyInspection.Create(applicationId, inspectorId); await inspections.AddAsync(inspection, ct); await inspections.SaveAsync(ct); return Map(inspection); }
    public async Task<PropertyInspectionDto?> GetAsync(Guid id, CancellationToken ct) { var x = await inspections.FindAsync(id, ct); return x is null ? null : Map(x); }
    public async Task<IReadOnlyList<PropertyInspectionDto>> ListAsync(Guid applicationId, CancellationToken ct) => (await inspections.FindByApplicationAsync(applicationId, ct)).Select(Map).ToArray();
    public async Task<PropertyInspectionDto?> EditAsync(Guid id, EditInspection input, byte[] expected, CancellationToken ct) { var x = await inspections.FindAsync(id, ct); if (x is null) return null; inspections.Expect(x, expected); x.Edit(input.Governorate, input.State, input.Area, input.NumberOfFloors, input.NumberOfRooms, input.PropertyArea, input.PropertyCondition, input.InspectionDate, input.Result, input.Notes); await inspections.SaveAsync(ct); return Map(x); }
    public async Task<PropertyInspectionDto?> CompleteAsync(Guid id, Guid actor, byte[] expected, CancellationToken ct) { var x = await inspections.FindAsync(id, ct); if (x is null) return null; inspections.Expect(x, expected); x.Complete(actor); await inspections.SaveAsync(ct); return Map(x); }
    public async Task<PropertyInspectionDto?> DecideAsync(Guid id, Guid actor, bool approve, string? reason, byte[] expected, CancellationToken ct) { var x = await inspections.FindAsync(id, ct); if (x is null) return null; inspections.Expect(x, expected); var app = await applications.FindAsync(x.LoanApplicationId, ct) ?? throw new LoanApplicationStateException(); if (approve) { x.Approve(actor); app.MarkInspectionApproved(); } else { x.Reject(actor, reason); app.MarkInspectionRejected(); } await inspections.SaveAsync(ct); return Map(x); }
    public static PropertyInspectionDto Map(PropertyInspection x) => new(x.Id, x.LoanApplicationId, x.InspectorId, x.Governorate, x.State, x.Area, x.NumberOfFloors, x.NumberOfRooms, x.PropertyArea, x.PropertyCondition, x.InspectionDate, x.Result, x.Status.ToString(), x.Notes, x.CreatedAtUtc, x.UpdatedAtUtc, x.FinalizedAtUtc, Convert.ToBase64String(x.RowVersion));
}
