using LoanSystem.Modules.LoanProducts.Domain;
namespace LoanSystem.DomainTests;

public sealed class LoanProductTests
{
    static EligibilityConfiguration Eligibility() => new("configured-nationality", 2, [new("configured-grade", 5000m)], new(120, "configured-rule"));
    static LoanProductVersion Draft(decimal amount = 10000m, decimal percentage = 30m, IEnumerable<string>? types = null, DateOnly? from = null, DateOnly? to = null) => LoanProduct.Create("Product").CreateDraftVersion(1, amount, "OMR", percentage, types ?? ["Purchase Existing House", "Build New House"], Eligibility(), from ?? new(2026, 1, 1), to);
    [Fact] public void Product_status_transitions_are_independent() { var p = LoanProduct.Create("Officers"); Assert.Equal(LoanProductStatus.Active, p.Status); p.Deactivate(); Assert.Equal(LoanProductStatus.Inactive, p.Status); p.Activate(); Assert.Equal(LoanProductStatus.Active, p.Status); }
    [Fact] public void Draft_is_editable_and_publish_is_one_way() { var v = Draft(); v.Edit(9000, "usd", 40, ["Configured type"], Eligibility(), new(2027, 1, 1), new(2027, 12, 31)); Assert.Equal(9000, v.MaximumAmount); v.Publish(); Assert.Equal(LoanProductVersionStatus.Published, v.Status); Assert.NotNull(v.PublishedAtUtc); Assert.Throws<LoanProductVersionImmutableException>(() => v.Edit(1, "OMR", 1, ["x"], Eligibility(), new(2027, 1, 1), null)); Assert.Throws<LoanProductInvalidStateException>(() => v.Publish()); }
    [Theory][InlineData(0)][InlineData(-1)] public void Maximum_amount_must_be_positive(decimal value) => Assert.Throws<LoanProductValidationException>(() => Draft(value));
    [Theory][InlineData(-0.1)][InlineData(100.1)] public void Percentage_uses_explicit_zero_to_one_hundred_units(decimal value) => Assert.Throws<LoanProductValidationException>(() => Draft(100, value));
    [Fact] public void Effective_period_must_be_ordered() => Assert.Throws<LoanProductValidationException>(() => Draft(from: new(2027, 2, 1), to: new(2027, 1, 1)));
    [Fact] public void Financing_types_are_case_insensitively_unique() => Assert.Throws<LoanProductValidationException>(() => Draft(types: ["Build", "build"]));
    [Fact] public void Draft_edit_preserves_unchanged_financing_children_and_replaces_only_changed_values() { var version = Draft(types: ["Keep", "Remove"]); var unchanged = version.FinancingTypes.Single(value => value.Value == "Keep"); version.Edit(10000, "OMR", 30, ["keep", "Add"], Eligibility(), new(2026, 1, 1), null); Assert.Same(unchanged, version.FinancingTypes.Single(value => value.Value == "Keep")); Assert.Equal(["Add", "Keep"], version.FinancingTypes.Select(value => value.Value).Order().ToArray()); }
    [Fact] public void Rank_rules_are_unique_positive_and_within_product_limit() { var bad = new EligibilityConfiguration("x", 1, [new("G", 1), new("g", 2)], new(1, "rule")); Assert.Throws<LoanProductValidationException>(() => LoanProduct.Create("Product").CreateDraftVersion(1, 10, "OMR", 1, ["x"], bad, new(2026, 1, 1), null)); }
    [Fact] public void Eligibility_is_structurally_required() { var bad = new EligibilityConfiguration("", 0, [], new(0, "")); Assert.Throws<LoanProductValidationException>(() => LoanProduct.Create("Product").CreateDraftVersion(1, 10, "OMR", 1, ["x"], bad, new(2026, 1, 1), null)); }
    [Fact] public void Aggregate_collections_and_eligibility_rules_are_defensively_owned() { var sourceRules = new List<RankGradeAmountRule> { new("Configured", 5000) }; var sourceTypes = new List<string> { "Configured type" }; var eligibility = new EligibilityConfiguration("Configured", 2, sourceRules, new(12, "Configured")); var product = LoanProduct.Create("Product"); var version = product.CreateDraftVersion(1, 10000, "OMR", 20, sourceTypes, eligibility, new(2026, 1, 1), null); version.Publish(); sourceRules.Add(new("External mutation", 1)); sourceTypes.Add("External type"); Assert.Single(version.EligibilityConfiguration.RankGradeAmountRules); Assert.Single(version.FinancingTypes); Assert.Throws<NotSupportedException>(() => ((ICollection<LoanProductVersion>)product.Versions).Add(Draft())); Assert.Throws<NotSupportedException>(() => ((ICollection<LoanProductFinancingType>)version.FinancingTypes).Clear()); Assert.Equal(LoanProductVersionStatus.Published, version.Status); }
}
