using LoanSystem.Modules.LoanOrigination.Domain;
namespace LoanSystem.DomainTests;

public sealed class LoanApplicationPrerequisiteTests
{
    [Fact] public void All_prerequisites_make_ready_and_detach_returns_pending() { var a = CommitteeApproved(); a.BeginPrerequisites(); a.MarkInspectionApproved(); a.AttachDocument(Guid.NewGuid(), ApplicationDocumentType.Ownership); a.AttachDocument(Guid.NewGuid(), ApplicationDocumentType.Survey); var drawing = Guid.NewGuid(); a.AttachDocument(drawing, ApplicationDocumentType.EngineeringDrawing); Assert.Equal(DocumentPrerequisiteStatus.Satisfied, a.DocumentPrerequisiteStatus); a.CompleteMortgage(Guid.NewGuid()); Assert.Equal(LoanApplicationStatus.ReadyForFinalApproval, a.Status); a.DetachDocument(drawing); Assert.Equal(LoanApplicationStatus.PrerequisitesPending, a.Status); Assert.Equal(DocumentPrerequisiteStatus.Pending, a.DocumentPrerequisiteStatus); }
    [Fact] public void Mortgage_waiver_requires_reason() { var a = CommitteeApproved(); a.BeginPrerequisites(); a.MarkInspectionApproved(); Assert.Throws<MortgageReasonRequiredException>(() => a.WaiveMortgage(Guid.NewGuid(), " ")); a.WaiveMortgage(Guid.NewGuid(), "No security required"); Assert.Equal(MortgageStatus.NotRequired, a.MortgageStatus); }
    [Fact] public void Inspection_rejection_does_not_reject_application() { var a = CommitteeApproved(); a.BeginPrerequisites(); a.MarkInspectionRejected(); Assert.Equal(InspectionPrerequisiteStatus.Rejected, a.InspectionPrerequisiteStatus); Assert.Equal(LoanApplicationStatus.PrerequisitesPending, a.Status); }
    private static LoanApplication CommitteeApproved() { var product = new ProductSnapshot(Guid.NewGuid(), Guid.NewGuid(), "Housing", 1, 100000, "OMR", 10, ["Build"], new("OM", 1, [], 240, "Monthly"), DateOnly.MinValue, null, "Active", "Published", DateTimeOffset.UtcNow); var a = LoanApplication.Create(Guid.NewGuid(), product, 50000, "Build", new("C", null, "Name", null, "OM", "MOD", null, null, "Active")); a.EvaluateEligibility(0); a.Submit(); a.ApproveByUnit(Guid.NewGuid()); a.ApproveByCommittee(Guid.NewGuid()); return a; }
}
