using LoanSystem.Modules.LoanOrigination.Domain;
namespace LoanSystem.DomainTests;

public sealed class LoanApplicationTests
{
    static ProductSnapshot Product(string[]? types = null) => new(Guid.NewGuid(), Guid.NewGuid(), "Housing", 1, 100000m, "OMR", 10m, types ?? ["Build"], new("OM", 1, [new("A", 100000m)], 240, "Monthly"), new(2026, 1, 1), null, "Active", "Published", DateTimeOffset.UtcNow);
    static BorrowerSnapshot Borrower() => new("1", "E1", "Original", null, "OM", "MOD", "A", "Active employee", "Active");
    [Fact] public void New_application_is_draft_and_owns_snapshot_collections() { var types = new[] { "Build" }; var a = LoanApplication.Create(Guid.NewGuid(), Product(types), 100m, "Build", Borrower()); types[0] = "Other"; Assert.Equal(LoanApplicationStatus.Draft, a.Status); Assert.Equal("Build", a.ProductSnapshot.FinancingTypes.Single()); }
    [Theory][InlineData(0)][InlineData(-1)][InlineData(100001)] public void Invalid_amount_is_rejected(decimal amount) => Assert.Throws<LoanApplicationValidationException>(() => LoanApplication.Create(Guid.NewGuid(), Product(), amount, "Build", Borrower()));
    [Fact] public void Financing_type_must_belong_to_version() => Assert.Throws<LoanApplicationValidationException>(() => LoanApplication.Create(Guid.NewGuid(), Product(), 100m, "Purchase", Borrower()));
    [Fact] public void Draft_edit_changes_only_editable_values() { var a = LoanApplication.Create(Guid.NewGuid(), Product(), 100m, "Build", Borrower()); var snapshot = a.BorrowerSnapshot; a.EditDraft(200m, "Build"); Assert.Equal(200m, a.RequestedAmount); Assert.Same(snapshot, a.BorrowerSnapshot); Assert.Equal(LoanApplicationStatus.Draft, a.Status); }
    [Fact] public void Eligibility_uses_snapshots_and_calculates_rank_cap() { var a = LoanApplication.Create(Guid.NewGuid(), Product(), 700m, "Build", Borrower()); var d = a.EvaluateEligibility(0, DateTimeOffset.UnixEpoch); Assert.True(d.IsEligible); Assert.Equal(100000m, d.PermittedAmount); Assert.Equal(a.LoanProductVersionId, d.AppliedLoanProductVersionId); Assert.Equal(0, d.ObservedConflictingApplicationCount); Assert.All(d.RuleResults, x => Assert.True(x.Passed)); }
    [Fact] public void Eligibility_reports_all_stable_failure_reasons() { var p = Product() with { EligibilityConfiguration = new("OM", 1, [new("B", 500m)], 240, "Monthly") }; var a = LoanApplication.Create(Guid.NewGuid(), p, 600m, "Build", Borrower() with { Nationality = " XX ", RankGrade = "A" }); var d = a.EvaluateEligibility(1); Assert.False(d.IsEligible); Assert.Contains(d.RuleResults, x => x.ReasonCode == EligibilityReasonCodes.NationalityMismatch); Assert.Contains(d.RuleResults, x => x.ReasonCode == EligibilityReasonCodes.ApplicationCountExceeded); Assert.Contains(d.RuleResults, x => x.ReasonCode == EligibilityReasonCodes.RankGradeNotConfigured); }
    [Fact] public void Requested_amount_above_matching_rank_cap_fails() { var p = Product() with { EligibilityConfiguration = new("OM", 1, [new("A", 500m)], 240, "Monthly") }; var d = LoanApplication.Create(Guid.NewGuid(), p, 600m, "Build", Borrower()).EvaluateEligibility(0); Assert.False(d.IsEligible); Assert.Equal(500m, d.PermittedAmount); Assert.Contains(d.RuleResults, x => x.ReasonCode == EligibilityReasonCodes.RequestedAmountExceedsPermitted); }
    [Fact] public void Eligibility_is_case_insensitive_and_product_max_caps_rank() { var p = Product() with { MaximumAmount = 1000m, EligibilityConfiguration = new(" om ", 1, [new(" a ", 2000m)], 240, "Monthly") }; var a = LoanApplication.Create(Guid.NewGuid(), p, 1000m, "Build", Borrower()); Assert.Equal(1000m, a.EvaluateEligibility(0).PermittedAmount); }
    [Fact] public void No_rank_rules_uses_product_maximum() { var p = Product() with { EligibilityConfiguration = new("", 0, [], 240, "Monthly") }; var a = LoanApplication.Create(Guid.NewGuid(), p, 1000m, "Build", Borrower()); var d = a.EvaluateEligibility(20); Assert.True(d.IsEligible); Assert.Equal(p.MaximumAmount, d.PermittedAmount); }
    [Fact] public void Edit_invalidates_decision() { var a = LoanApplication.Create(Guid.NewGuid(), Product(), 100m, "Build", Borrower()); a.EvaluateEligibility(0); a.EditDraft(200m, "Build"); Assert.Null(a.EligibilityDecision); }
    [Fact] public void Submit_requires_eligible_current_evaluation_and_raises_fact() { var a = LoanApplication.Create(Guid.NewGuid(), Product(), 100m, "Build", Borrower()); Assert.Throws<EligibilityRequiredException>(() => a.Submit()); a.EvaluateEligibility(0); var fact = a.Submit(DateTimeOffset.UnixEpoch); Assert.Equal(LoanApplicationStatus.Submitted, a.Status); Assert.Equal(DateTimeOffset.UnixEpoch, a.SubmittedAtUtc); Assert.Equal(a.Id, fact.LoanApplicationId); Assert.Single(a.DomainEvents); Assert.Throws<LoanApplicationStateException>(() => a.EditDraft(100m, "Build")); Assert.Throws<LoanApplicationStateException>(() => a.EvaluateEligibility(0)); Assert.Throws<LoanApplicationStateException>(() => a.Submit()); }
    [Fact] public void Ineligible_decision_cannot_submit() { var a = LoanApplication.Create(Guid.NewGuid(), Product(), 100m, "Build", Borrower() with { Nationality = "XX" }); a.EvaluateEligibility(0); Assert.Throws<LoanApplicationIneligibleException>(() => a.Submit()); }
    static LoanApplication Submitted() { var a = LoanApplication.Create(Guid.NewGuid(), Product(), 100m, "Build", Borrower()); a.EvaluateEligibility(0); a.Submit(); return a; }
    [Fact] public void Unit_approval_captures_actor_time_comment_and_fact() { var a = Submitted(); var actor = Guid.NewGuid(); var at = DateTimeOffset.UnixEpoch.AddDays(1); var fact = a.ApproveByUnit(actor, " reviewed ", at); Assert.Equal(LoanApplicationStatus.UnitApproved, a.Status); Assert.Equal(UnitDecision.Approved, a.UnitApproval!.Decision); Assert.Equal(actor, a.UnitApproval.ActorUserId); Assert.Equal(at, a.UnitApproval.DecidedAtUtc); Assert.Equal("reviewed", a.UnitApproval.Comment); Assert.Null(a.UnitApproval.RejectionReason); Assert.Equal(at, a.UpdatedAtUtc); Assert.Equal(a.Id, fact.LoanApplicationId); Assert.IsType<UnitApprovalGranted>(a.DomainEvents[^1]); }
    [Fact] public void Unit_approval_comment_is_optional() { var a = Submitted(); a.ApproveByUnit(Guid.NewGuid(), "  "); Assert.Null(a.UnitApproval!.Comment); }
    [Fact] public void Unit_rejection_captures_actor_time_reason_and_fact() { var a = Submitted(); var actor = Guid.NewGuid(); var at = DateTimeOffset.UnixEpoch.AddDays(2); var fact = a.RejectByUnit(actor, " incomplete ", at); Assert.Equal(LoanApplicationStatus.Rejected, a.Status); Assert.Equal(UnitDecision.Rejected, a.UnitApproval!.Decision); Assert.Equal(actor, a.UnitApproval.ActorUserId); Assert.Equal("incomplete", a.UnitApproval.RejectionReason); Assert.Null(a.UnitApproval.Comment); Assert.Equal(at, a.RejectedAtUtc); Assert.Equal(at, a.UpdatedAtUtc); Assert.Equal("Unit", fact.Stage); Assert.IsType<LoanApplicationRejected>(a.DomainEvents[^1]); }
    [Theory][InlineData(null)][InlineData("")][InlineData("   ")] public void Unit_rejection_requires_reason(string? reason) { var a = Submitted(); Assert.Throws<RejectionReasonRequiredException>(() => a.RejectByUnit(Guid.NewGuid(), reason)); Assert.Equal(LoanApplicationStatus.Submitted, a.Status); Assert.Null(a.UnitApproval); }
    [Fact] public void Unit_decision_requires_actor() { var a = Submitted(); Assert.Throws<InvalidActorException>(() => a.ApproveByUnit(Guid.Empty)); Assert.Throws<InvalidActorException>(() => a.RejectByUnit(Guid.Empty, "reason")); }
    [Fact] public void Draft_cannot_receive_unit_decision() { var a = LoanApplication.Create(Guid.NewGuid(), Product(), 100m, "Build", Borrower()); Assert.Throws<LoanApplicationStateException>(() => a.ApproveByUnit(Guid.NewGuid())); Assert.Throws<LoanApplicationStateException>(() => a.RejectByUnit(Guid.NewGuid(), "reason")); }
    [Fact] public void Unit_decision_is_terminal_for_this_step() { var approved = Submitted(); approved.ApproveByUnit(Guid.NewGuid()); Assert.Throws<LoanApplicationStateException>(() => approved.ApproveByUnit(Guid.NewGuid())); Assert.Throws<LoanApplicationStateException>(() => approved.RejectByUnit(Guid.NewGuid(), "reason")); var rejected = Submitted(); rejected.RejectByUnit(Guid.NewGuid(), "reason"); Assert.Throws<LoanApplicationStateException>(() => rejected.RejectByUnit(Guid.NewGuid(), "again")); Assert.Throws<LoanApplicationStateException>(() => rejected.ApproveByUnit(Guid.NewGuid())); }
}
