using LoanSystem.Modules.LoanAccounts.Domain;
using LoanSystem.Modules.LoanOrigination.Domain;
namespace LoanSystem.DomainTests;

public sealed class Task11DomainTests
{
    [Fact] public void Ready_application_is_finally_approved_and_raises_stable_fact() { var a = Ready(); var actor = Guid.NewGuid(); var fact = a.FinalApprove(actor, DateTimeOffset.UnixEpoch); Assert.Equal(LoanApplicationStatus.Approved, a.Status); Assert.Equal(a.Id, fact.LoanApplicationId); Assert.Equal(a.RequestedAmount, fact.ApprovedAmount); Assert.Equal(actor, fact.ActorUserId); Assert.NotEqual(Guid.Empty, fact.EventId); Assert.Same(fact, a.DomainEvents[^1]); }
    [Fact] public void Final_approval_is_not_repeatable() { var a = Ready(); a.FinalApprove(Guid.NewGuid()); Assert.Throws<FinalApprovalPrerequisitesException>(() => a.FinalApprove(Guid.NewGuid())); }
    [Fact] public void Every_non_ready_state_is_rejected() { var draft = Create(); Assert.Throws<FinalApprovalPrerequisitesException>(() => draft.FinalApprove(Guid.NewGuid())); var submitted = Create(); submitted.EvaluateEligibility(0); submitted.Submit(); Assert.Throws<FinalApprovalPrerequisitesException>(() => submitted.FinalApprove(Guid.NewGuid())); var unit = Create(); unit.EvaluateEligibility(0); unit.Submit(); unit.ApproveByUnit(Guid.NewGuid()); Assert.Throws<FinalApprovalPrerequisitesException>(() => unit.FinalApprove(Guid.NewGuid())); var committee = Committee(); Assert.Throws<FinalApprovalPrerequisitesException>(() => committee.FinalApprove(Guid.NewGuid())); var pending = Committee(); pending.BeginPrerequisites(); Assert.Throws<FinalApprovalPrerequisitesException>(() => pending.FinalApprove(Guid.NewGuid())); var rejected = Create(); rejected.EvaluateEligibility(0); rejected.Submit(); rejected.RejectByUnit(Guid.NewGuid(), "no"); Assert.Throws<FinalApprovalPrerequisitesException>(() => rejected.FinalApprove(Guid.NewGuid())); }
    [Fact] public void Empty_actor_cannot_finally_approve() => Assert.Throws<InvalidActorException>(() => Ready().FinalApprove(Guid.Empty));
    [Fact] public void Loan_account_opens_with_zero_totals_and_correct_derived_values() { var source = Guid.NewGuid(); var loan = LoanAccount.Open(source, Guid.NewGuid(), Guid.NewGuid(), Guid.NewGuid(), 123.45m, "omr", "Build", DateTimeOffset.UnixEpoch); Assert.Equal(source, loan.SourceApplicationId); Assert.Equal(123.45m, loan.ApprovedAmount); Assert.Equal(123.45m, loan.AvailableToDisburse); Assert.Equal(0m, loan.ReservedDisbursementAmount); Assert.Equal(0m, loan.TotalDisbursed); Assert.Equal(0m, loan.TotalRepaid); Assert.Equal(0m, loan.OutstandingBalance); Assert.Equal(LoanAccountStatus.Active, loan.Status); Assert.Equal("OMR", loan.Currency); Assert.IsType<LoanAccountOpened>(loan.DomainEvents.Single()); }
    [Theory][InlineData(0)][InlineData(-1)] public void Loan_account_rejects_invalid_approved_amount(decimal amount) => Assert.Throws<LoanAccountValidationException>(() => LoanAccount.Open(Guid.NewGuid(), Guid.NewGuid(), Guid.NewGuid(), Guid.NewGuid(), amount, "OMR", "Build"));
    private static LoanApplication Create() { var p = new ProductSnapshot(Guid.NewGuid(), Guid.NewGuid(), "Housing", 1, 100000, "OMR", 10, ["Build"], new("OM", 1, [], 240, "Monthly"), DateOnly.MinValue, null, "Active", "Published", DateTimeOffset.UtcNow); return LoanApplication.Create(Guid.NewGuid(), p, 50000, "Build", new("C", null, "Name", null, "OM", "MOD", null, null, "Active")); }
    private static LoanApplication Committee() { var a = Create(); a.EvaluateEligibility(0); a.Submit(); a.ApproveByUnit(Guid.NewGuid()); a.ApproveByCommittee(Guid.NewGuid()); return a; }
    private static LoanApplication Ready() { var a = Committee(); a.BeginPrerequisites(); a.MarkInspectionApproved(); a.AttachDocument(Guid.NewGuid(), LoanApplicationDocumentType.Ownership); a.AttachDocument(Guid.NewGuid(), LoanApplicationDocumentType.Survey); a.AttachDocument(Guid.NewGuid(), LoanApplicationDocumentType.EngineeringDrawing); a.CompleteMortgage(Guid.NewGuid()); return a; }
}
