<Project>
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework><Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings><TreatWarningsAsErrors>true</TreatWarningsAsErrors><AnalysisLevel>latest-recommended</AnalysisLevel><Deterministic>true</Deterministic><NoWarn>$(NoWarn);CA1707;CA1050</NoWarn>
  </PropertyGroup>
</Project>
