using System.Text.Json;
using LoanSystem.Modules.LoanOrigination.Application;
using LoanSystem.Modules.LoanOrigination.Domain;
using Microsoft.EntityFrameworkCore;
namespace LoanSystem.Modules.LoanOrigination.Infrastructure;

public sealed class LoanOriginationDbContext(DbContextOptions<LoanOriginationDbContext> options) : DbContext(options), ILoanApplicationStore
{
    public DbSet<LoanApplication> LoanApplications => Set<LoanApplication>();
    protected override void OnModelCreating(ModelBuilder modelBuilder) { var b = modelBuilder.Entity<LoanApplication>(); b.ToTable("loan_applications", "loan_origination"); b.HasKey(x => x.Id); b.Ignore(x => x.DomainEvents); b.Property(x => x.Id).HasColumnName("loan_application_id"); b.Property(x => x.BorrowerId).HasColumnName("borrower_id"); b.Property(x => x.LoanProductId).HasColumnName("loan_product_id"); b.Property(x => x.LoanProductVersionId).HasColumnName("loan_product_version_id"); b.Property(x => x.RequestedAmount).HasColumnName("requested_amount").HasPrecision(19, 4); b.Property(x => x.Currency).HasColumnName("currency").HasColumnType("char(3)"); b.Property(x => x.FinancingType).HasColumnName("financing_type").HasMaxLength(100); b.Property(x => x.Status).HasColumnName("status").HasConversion<string>().HasMaxLength(30); b.Property(x => x.BorrowerSnapshot).HasColumnName("borrower_snapshot").HasColumnType("nvarchar(max)").HasConversion(x => JsonSerializer.Serialize(x, JsonSerializerOptions.Default), x => JsonSerializer.Deserialize<BorrowerSnapshot>(x, JsonSerializerOptions.Default)!); b.Property(x => x.ProductSnapshot).HasColumnName("product_snapshot").HasColumnType("nvarchar(max)").HasConversion(x => JsonSerializer.Serialize(x, JsonSerializerOptions.Default), x => JsonSerializer.Deserialize<ProductSnapshot>(x, JsonSerializerOptions.Default)!); b.Property(x => x.EligibilityDecision).HasColumnName("eligibility_snapshot").HasColumnType("nvarchar(max)").HasConversion(x => x == null ? null : JsonSerializer.Serialize(x, JsonSerializerOptions.Default), x => x == null ? null : JsonSerializer.Deserialize<EligibilityDecision>(x, JsonSerializerOptions.Default)); b.Property(x => x.CreatedAtUtc).HasColumnName("created_at_utc"); b.Property(x => x.UpdatedAtUtc).HasColumnName("updated_at_utc"); b.Property(x => x.SubmittedAtUtc).HasColumnName("submitted_at_utc"); b.Property(x => x.RowVersion).HasColumnName("row_version").IsRowVersion(); b.HasIndex(x => x.BorrowerId).HasDatabaseName("IX_loan_applications_borrower_id"); b.HasIndex(x => x.LoanProductId).HasDatabaseName("IX_loan_applications_product_id"); b.HasIndex(x => x.Status).HasDatabaseName("IX_loan_applications_status"); b.HasIndex(x => x.CreatedAtUtc).HasDatabaseName("IX_loan_applications_created_at"); }
    public Task AddAsync(LoanApplication value, CancellationToken ct) => LoanApplications.AddAsync(value, ct).AsTask();
    public Task<LoanApplication?> FindAsync(Guid id, CancellationToken ct) => LoanApplications.SingleOrDefaultAsync(x => x.Id == id, ct);
    public Task<int> CountConflictingApplicationsAsync(Guid borrowerId, Guid excludeApplicationId, CancellationToken ct) => LoanApplications.AsNoTracking().CountAsync(x => x.BorrowerId == borrowerId && x.Id != excludeApplicationId && (x.Status == LoanApplicationStatus.Draft || x.Status == LoanApplicationStatus.Submitted), ct);
    public void Expect(LoanApplication value, byte[] expected) => Entry(value).Property(x => x.RowVersion).OriginalValue = expected;
    public async Task SaveAsync(CancellationToken ct) { try { await SaveChangesAsync(ct); } catch (DbUpdateConcurrencyException) { throw new LoanApplicationConcurrencyException(); } }
    public async Task<LoanApplicationPage> SearchAsync(LoanApplicationSearch search, CancellationToken ct) { var q = LoanApplications.AsNoTracking(); if (search.LoanApplicationId.HasValue) q = q.Where(x => x.Id == search.LoanApplicationId); if (search.BorrowerId.HasValue) q = q.Where(x => x.BorrowerId == search.BorrowerId); if (search.LoanProductId.HasValue) q = q.Where(x => x.LoanProductId == search.LoanProductId); if (search.Status.HasValue) q = q.Where(x => x.Status == search.Status); var count = await q.CountAsync(ct); var values = await q.OrderByDescending(x => x.CreatedAtUtc).ThenBy(x => x.Id).Skip((search.PageNumber - 1) * search.PageSize).Take(search.PageSize).ToListAsync(ct); var rows = values.Select(x => new LoanApplicationListItem(x.Id, x.BorrowerId, x.BorrowerSnapshot.FullName, x.LoanProductId, x.ProductSnapshot.ProductName, x.RequestedAmount, x.Currency, x.FinancingType, x.Status.ToString(), x.CreatedAtUtc)).ToArray(); return new(rows, search.PageNumber, search.PageSize, count); }
}
