using System.Data;
using System.Text.Json;
using LoanSystem.Contracts;
using LoanSystem.Modules.LoanProducts.Application;
using LoanSystem.Modules.LoanProducts.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
namespace LoanSystem.Modules.LoanProducts.Infrastructure;

public sealed class LoanProductsDbContext(DbContextOptions<LoanProductsDbContext> options) : DbContext(options), ILoanProductStore
{
 public DbSet<LoanProduct> Products=>Set<LoanProduct>(); public DbSet<LoanProductVersion> Versions=>Set<LoanProductVersion>();
 protected override void OnModelCreating(ModelBuilder b){b.ApplyConfiguration(new ProductConfiguration());b.ApplyConfiguration(new VersionConfiguration());b.ApplyConfiguration(new FinancingTypeConfiguration());}
 public Task AddAsync(LoanProduct p,CancellationToken ct)=>Products.AddAsync(p,ct).AsTask();
 public Task<LoanProduct?> FindAsync(Guid id,CancellationToken ct)=>Products.Include(x=>x.Versions).ThenInclude(x=>x.FinancingTypes).SingleOrDefaultAsync(x=>x.Id==id,ct);
 public Task<LoanProductVersion?> FindVersionAsync(Guid productId,Guid versionId,CancellationToken ct)=>Versions.Include(x=>x.FinancingTypes).SingleOrDefaultAsync(x=>x.LoanProductId==productId&&x.Id==versionId,ct);
 public async Task<IReadOnlyList<ProductListItem>> ListAsync(CancellationToken ct)=>await Products.AsNoTracking().OrderBy(x=>x.Name).Select(x=>new ProductListItem(x.Id,x.Name,x.Status==LoanProductStatus.Active?"Active":"Inactive",x.Versions.Count,x.Versions.Select(v=>(int?)v.VersionNumber).Max())).ToListAsync(ct);
 public async Task<IReadOnlyList<AvailableProductVersion>> AvailableAsync(DateOnly today,CancellationToken ct)=>await Versions.AsNoTracking().Where(v=>v.Status==LoanProductVersionStatus.Published&&v.EffectiveFrom<=today&&(!v.EffectiveTo.HasValue||v.EffectiveTo>=today)&&Products.Any(p=>p.Id==v.LoanProductId&&p.Status==LoanProductStatus.Active)).OrderBy(v=>v.LoanProductId).ThenBy(v=>v.VersionNumber).Select(v=>new AvailableProductVersion(v.LoanProductId,v.Id,Products.Where(p=>p.Id==v.LoanProductId).Select(p=>p.Name).Single(),v.VersionNumber,v.MaximumAmount,v.Currency,v.DeductionPercentage,v.FinancingTypes.Select(f=>f.Value).ToArray(),v.EffectiveFrom,v.EffectiveTo)).ToListAsync(ct);
 public async Task<int> NextVersionNumberAsync(Guid productId,CancellationToken ct){if(Database.CurrentTransaction is null)await Database.BeginTransactionAsync(IsolationLevel.Serializable,ct);return (await Versions.Where(x=>x.LoanProductId==productId).MaxAsync(x=>(int?)x.VersionNumber,ct)??0)+1;}
 public Task<bool> OverlapsAsync(Guid productId,Guid except,DateOnly from,DateOnly? to,CancellationToken ct)=>Versions.AnyAsync(x=>x.LoanProductId==productId&&x.Id!=except&&x.Status==LoanProductVersionStatus.Published&&(!x.EffectiveTo.HasValue||x.EffectiveTo>=from)&&(!to.HasValue||x.EffectiveFrom<=to),ct);
 public void Expect(LoanProduct p,byte[] v)=>Entry(p).Property(x=>x.RowVersion).OriginalValue=v; public void Expect(LoanProductVersion p,byte[] v)=>Entry(p).Property(x=>x.RowVersion).OriginalValue=v;
 public async Task SaveAsync(CancellationToken ct){try{await SaveChangesAsync(ct);if(Database.CurrentTransaction is not null)await Database.CommitTransactionAsync(ct);}catch(DbUpdateConcurrencyException){throw new LoanProductConcurrencyException();}}
}
internal sealed class ProductConfiguration:IEntityTypeConfiguration<LoanProduct>{public void Configure(EntityTypeBuilder<LoanProduct>b){b.ToTable("loan_products","loan_products");b.HasKey(x=>x.Id);b.Property(x=>x.Id).HasColumnName("loan_product_id");b.Property(x=>x.Name).HasColumnName("name").HasMaxLength(200).IsRequired();b.Property(x=>x.Status).HasColumnName("status").HasConversion<string>().HasMaxLength(20);b.Property(x=>x.CreatedAtUtc).HasColumnName("created_at_utc");b.Property(x=>x.UpdatedAtUtc).HasColumnName("updated_at_utc");b.Property(x=>x.RowVersion).HasColumnName("row_version").IsRowVersion();b.HasMany(x=>x.Versions).WithOne().HasForeignKey(x=>x.LoanProductId).OnDelete(DeleteBehavior.Restrict);}}
internal sealed class VersionConfiguration:IEntityTypeConfiguration<LoanProductVersion>{public void Configure(EntityTypeBuilder<LoanProductVersion>b){b.ToTable("loan_product_versions","loan_products");b.HasKey(x=>x.Id);b.Property(x=>x.Id).HasColumnName("version_id");b.Property(x=>x.LoanProductId).HasColumnName("loan_product_id");b.Property(x=>x.VersionNumber).HasColumnName("version_number");b.HasIndex(x=>new{x.LoanProductId,x.VersionNumber}).IsUnique();b.Property(x=>x.MaximumAmount).HasColumnName("maximum_amount").HasPrecision(19,4);b.Property(x=>x.Currency).HasColumnName("currency").HasColumnType("char(3)");b.Property(x=>x.DeductionPercentage).HasColumnName("deduction_percentage").HasPrecision(9,4);var options=new JsonSerializerOptions(JsonSerializerDefaults.Web);b.Property(x=>x.EligibilityConfiguration).HasColumnName("eligibility_configuration").HasColumnType("nvarchar(max)").HasConversion(x=>JsonSerializer.Serialize(x,options),x=>JsonSerializer.Deserialize<EligibilityConfiguration>(x,options)!).Metadata.SetValueComparer(new ValueComparer<EligibilityConfiguration>((a,c)=>JsonSerializer.Serialize(a,options)==JsonSerializer.Serialize(c,options),a=>JsonSerializer.Serialize(a,options).GetHashCode(),a=>JsonSerializer.Deserialize<EligibilityConfiguration>(JsonSerializer.Serialize(a,options),options)!));b.Property(x=>x.EffectiveFrom).HasColumnName("effective_from").HasColumnType("date");b.Property(x=>x.EffectiveTo).HasColumnName("effective_to").HasColumnType("date");b.Property(x=>x.Status).HasColumnName("status").HasConversion<string>().HasMaxLength(20);b.Property(x=>x.PublishedAtUtc).HasColumnName("published_at_utc");b.Property(x=>x.CreatedAtUtc).HasColumnName("created_at_utc");b.Property(x=>x.RowVersion).HasColumnName("row_version").IsRowVersion();}}
internal sealed class FinancingTypeConfiguration:IEntityTypeConfiguration<LoanProductFinancingType>{public void Configure(EntityTypeBuilder<LoanProductFinancingType>b){b.ToTable("loan_product_financing_types","loan_products");b.HasKey(x=>new{x.VersionId,x.Value});b.Property(x=>x.VersionId).HasColumnName("version_id");b.Property(x=>x.Value).HasColumnName("financing_type").HasMaxLength(100);b.HasOne<LoanProductVersion>().WithMany(x=>x.FinancingTypes).HasForeignKey(x=>x.VersionId).OnDelete(DeleteBehavior.Cascade);}}

public sealed class LoanProductsModule(LoanProductsDbContext db):ILoanProductsModule
{public async Task<LoanProductVersionLookup> GetVersionAsync(Guid id,DateOnly date,CancellationToken ct=default){var v=await db.Versions.AsNoTracking().Include(x=>x.FinancingTypes).SingleOrDefaultAsync(x=>x.Id==id,ct);if(v is null)return new(LoanProductVersionLookupStatus.NotFound,null);var p=await db.Products.AsNoTracking().SingleAsync(x=>x.Id==v.LoanProductId,ct);var status=v.Status==LoanProductVersionStatus.Draft?LoanProductVersionLookupStatus.Draft:p.Status==LoanProductStatus.Inactive?LoanProductVersionLookupStatus.ProductInactive:v.EffectiveFrom>date||v.EffectiveTo<date?LoanProductVersionLookupStatus.OutsideEffectivePeriod:LoanProductVersionLookupStatus.Available;var e=v.EligibilityConfiguration;var dto=new LoanProductVersionContract(p.Id,v.Id,p.Name,v.VersionNumber,p.Status.ToString(),v.MaximumAmount,v.Currency,v.DeductionPercentage,v.FinancingTypes.Select(x=>x.Value).ToArray(),new(e.RequiredNationality,e.MaximumApplicationCount,e.RankGradeAmountRules.Select(x=>new LoanProductRankGradeRule(x.RankGrade,x.MaximumAmount)).ToArray(),e.Term.MaximumTermMonths,e.Term.DueDateRule),v.EffectiveFrom,v.EffectiveTo,v.Status.ToString(),v.PublishedAtUtc);return new(status,dto);}}
