<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\LoanSystem.Contracts\LoanSystem.Contracts.csproj" />
    <ProjectReference Include="..\BuildingBlocks\LoanSystem.BuildingBlocks.Infrastructure\LoanSystem.BuildingBlocks.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\IdentityAccess\LoanSystem.Modules.IdentityAccess\LoanSystem.Modules.IdentityAccess.csproj" />
    <ProjectReference Include="..\Modules\Borrowers\LoanSystem.Modules.Borrowers\LoanSystem.Modules.Borrowers.csproj" />
    <ProjectReference Include="..\Modules\LoanProducts\LoanSystem.Modules.LoanProducts\LoanSystem.Modules.LoanProducts.csproj" />
    <ProjectReference Include="..\Modules\LoanOrigination\LoanSystem.Modules.LoanOrigination\LoanSystem.Modules.LoanOrigination.csproj" />
    <ProjectReference Include="..\Modules\LoanAccounts\LoanSystem.Modules.LoanAccounts\LoanSystem.Modules.LoanAccounts.csproj" />
    <ProjectReference Include="..\Modules\Disbursements\LoanSystem.Modules.Disbursements\LoanSystem.Modules.Disbursements.csproj" />
    <ProjectReference Include="..\Modules\Treasury\LoanSystem.Modules.Treasury\LoanSystem.Modules.Treasury.csproj" />
    <ProjectReference Include="..\Modules\Repayments\LoanSystem.Modules.Repayments\LoanSystem.Modules.Repayments.csproj" />
    <ProjectReference Include="..\Modules\Documents\LoanSystem.Modules.Documents\LoanSystem.Modules.Documents.csproj" />
    <ProjectReference Include="..\Modules\Audit\LoanSystem.Modules.Audit\LoanSystem.Modules.Audit.csproj" />
    <ProjectReference Include="..\Modules\Reporting\LoanSystem.Modules.Reporting\LoanSystem.Modules.Reporting.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.21">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.21" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
