using System.Reflection;
namespace LoanSystem.ArchitectureTests;
public sealed class ArchitectureRulesTests
{
    private static readonly Assembly[] Modules = [typeof(Modules.IdentityAccess.ModuleMarker).Assembly, typeof(Modules.Borrowers.ModuleMarker).Assembly, typeof(Modules.LoanProducts.ModuleMarker).Assembly, typeof(Modules.LoanOrigination.ModuleMarker).Assembly, typeof(Modules.LoanAccounts.ModuleMarker).Assembly, typeof(Modules.Disbursements.ModuleMarker).Assembly, typeof(Modules.Treasury.ModuleMarker).Assembly, typeof(Modules.Repayments.ModuleMarker).Assembly, typeof(Modules.Documents.ModuleMarker).Assembly, typeof(Modules.Audit.ModuleMarker).Assembly, typeof(Modules.Reporting.ModuleMarker).Assembly];
    [Fact] public void Module_implementations_do_not_reference_each_other() { var names = Modules.Select(x => x.GetName().Name!).ToHashSet(); foreach (var module in Modules) Assert.Empty(module.GetReferencedAssemblies().Where(reference => reference.Name is not null && names.Contains(reference.Name))); }
    [Fact] public void Domain_does_not_depend_on_outer_layers() { foreach (var module in Modules) { var domainTypes = module.GetTypes().Where(type => type.Namespace?.EndsWith(".Domain", StringComparison.Ordinal) == true); foreach (var type in domainTypes) Assert.DoesNotContain(type.GetReferencedTypes(), dependency => dependency.Namespace?.Contains(".Application", StringComparison.Ordinal) == true || dependency.Namespace?.Contains(".Infrastructure", StringComparison.Ordinal) == true || dependency.Namespace?.Contains(".Presentation", StringComparison.Ordinal) == true); } }
}
internal static class ReflectionExtensions { public static IEnumerable<Type> GetReferencedTypes(this Type type) => type.GetFields(BindingFlags.Instance | BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic).Select(field => field.FieldType).Concat(type.GetProperties().Select(property => property.PropertyType)).Concat(type.GetMethods().Select(method => method.ReturnType)); }
