using LoanSystem.Modules.Documents.Application;
using LoanSystem.Modules.Documents.Domain;
using Microsoft.Extensions.Options;
namespace LoanSystem.ApplicationTests;

public sealed class DocumentApplicationTests
{
    [Theory][InlineData("../evil.pdf")][InlineData("..\\evil.pdf")][InlineData("/tmp/evil.pdf")][InlineData("a/../evil.pdf")] public async Task Rejects_path_traversal(string name) { var s = Service(); await Assert.ThrowsAsync<DocumentValidationException>(() => s.UploadAsync(name, "application/pdf", 1, new MemoryStream([1]), Guid.NewGuid(), default)); }
    [Fact] public async Task Rejects_size_and_type() { var s = Service(); await Assert.ThrowsAsync<DocumentValidationException>(() => s.UploadAsync("a.pdf", "application/pdf", 11, new MemoryStream(new byte[11]), Guid.NewGuid(), default)); await Assert.ThrowsAsync<DocumentValidationException>(() => s.UploadAsync("a.exe", "application/octet-stream", 1, new MemoryStream([1]), Guid.NewGuid(), default)); }
    [Fact] public async Task Compensates_storage_when_database_fails() { var storage = new FakeStorage(); var s = new DocumentService(new FakeRepo { Fail = true }, storage, Options.Create(new FileStorageOptions { MaximumFileSizeBytes = 10, AllowedContentTypes = ["text/plain"] }), new UploaderDocumentAccessAuthorizer()); await Assert.ThrowsAsync<InvalidOperationException>(() => s.UploadAsync("a.txt", "text/plain", 1, new MemoryStream([1]), Guid.NewGuid(), default)); Assert.True(storage.Deleted); }

    [Fact] public async Task Delete_marks_pending_before_removing_content_and_completes() { var events = new List<string>(); var repo = new FakeRepo { Events = events }; var storage = new FakeStorage { Events = events }; var document = NewDocument(); await new DocumentService(repo, storage, Config(), new UploaderDocumentAccessAuthorizer()).DeleteAsync(document, default); Assert.Collection(events, x => Assert.Equal("save", x), x => Assert.Equal("delete", x), x => Assert.Equal("save", x)); Assert.Equal(DocumentStatus.Deleted, document.Status); }
    [Fact] public async Task Delete_does_not_remove_content_when_pending_persistence_fails() { var repo = new FakeRepo { FailOnSave = 1 }; var storage = new FakeStorage(); var document = NewDocument(); await Assert.ThrowsAsync<InvalidOperationException>(() => new DocumentService(repo, storage, Config(), new UploaderDocumentAccessAuthorizer()).DeleteAsync(document, default)); Assert.False(storage.Deleted); }
    [Fact] public async Task Storage_failure_leaves_delete_pending_and_retry_completes() { var repo = new FakeRepo(); var storage = new FakeStorage { FailDelete = true }; var document = NewDocument(); var service = new DocumentService(repo, storage, Config(), new UploaderDocumentAccessAuthorizer()); await Assert.ThrowsAsync<IOException>(() => service.DeleteAsync(document, default)); Assert.Equal(DocumentStatus.DeletePending, document.Status); storage.FailDelete = false; await service.DeleteAsync(document, default); Assert.Equal(DocumentStatus.Deleted, document.Status); Assert.Equal(2, repo.SaveCount); }
    [Fact] public async Task Final_database_failure_never_returns_document_to_active() { var repo = new FakeRepo { FailOnSave = 2 }; var storage = new FakeStorage(); var document = NewDocument(); await Assert.ThrowsAsync<InvalidOperationException>(() => new DocumentService(repo, storage, Config(), new UploaderDocumentAccessAuthorizer()).DeleteAsync(document, default)); Assert.True(storage.Deleted); Assert.NotEqual(DocumentStatus.Active, document.Status); }
    static Document NewDocument() => Document.Create("a.txt", "text/plain", 1, Guid.NewGuid().ToString("N"), Guid.NewGuid());
    static IOptions<FileStorageOptions> Config() => Options.Create(new FileStorageOptions { MaximumFileSizeBytes = 10, AllowedContentTypes = ["text/plain"] });
    static DocumentService Service() => new(new FakeRepo(), new FakeStorage(), Options.Create(new FileStorageOptions { MaximumFileSizeBytes = 10, AllowedContentTypes = ["application/pdf"] }), new UploaderDocumentAccessAuthorizer());
    sealed class FakeStorage : IFileStorage { public bool Deleted; public bool FailDelete; public List<string>? Events; public Task StoreAsync(string k, Stream s, CancellationToken c) => Task.CompletedTask; public Task<Stream?> OpenReadAsync(string k, CancellationToken c) => Task.FromResult<Stream?>(null); public Task DeleteAsync(string k, CancellationToken c) { Events?.Add("delete"); if (FailDelete) throw new IOException(); Deleted = true; return Task.CompletedTask; } }
    sealed class FakeRepo : IDocumentRepository { public bool Fail; public int FailOnSave; public int SaveCount; public List<string>? Events; public Task AddAsync(Document d, CancellationToken c) => Task.CompletedTask; public Task<Document?> FindAsync(Guid i, CancellationToken c) => Task.FromResult<Document?>(null); public void Remove(Document d) { } public Task SaveAsync(CancellationToken c) { SaveCount++; Events?.Add("save"); return Fail || SaveCount == FailOnSave ? Task.FromException(new InvalidOperationException()) : Task.CompletedTask; } }
}
