using LoanSystem.Contracts;
using LoanSystem.Modules.LoanOrigination.Application;
using LoanSystem.Modules.LoanOrigination.Domain;
namespace LoanSystem.ApplicationTests;

public sealed class LoanApplicationServiceTests
{
    static BorrowerContract Borrower(bool active = true) => new(Guid.NewGuid(), "1", "E1", "Original", null, "OM", "MOD", "A", "Employment", active);
    static LoanProductVersionContract Product() => new(Guid.NewGuid(), Guid.NewGuid(), "Housing", 1, "Active", 1000m, "OMR", 10m, ["Build"], new("OM", 1, [new("A", 1000m)], 240, "Monthly"), DateOnly.FromDateTime(DateTime.UtcNow), null, "Published", DateTimeOffset.UtcNow);
    [Fact] public async Task Create_captures_contract_values() { var b = Borrower(); var p = Product(); var store = new Store(); var service = new LoanApplicationService(store, new Borrowers(b), new Products(new(LoanProductVersionLookupStatus.Available, p))); var result = await service.CreateAsync(new(b.BorrowerId, p.LoanProductVersionId, 500m, "Build"), default); Assert.Equal("Original", result.BorrowerSnapshot.FullName); Assert.Equal("Housing", result.ProductSnapshot.ProductName); Assert.Single(store.Values); }
    [Fact] public async Task Missing_and_inactive_borrowers_are_rejected() { var p = Product(); await Assert.ThrowsAsync<BorrowerUnavailableException>(() => new LoanApplicationService(new Store(), new Borrowers(null), new Products(new(LoanProductVersionLookupStatus.Available, p))).CreateAsync(new(Guid.NewGuid(), p.LoanProductVersionId, 1, "Build"), default)); var b = Borrower(false); await Assert.ThrowsAsync<BorrowerUnavailableException>(() => new LoanApplicationService(new Store(), new Borrowers(b), new Products(new(LoanProductVersionLookupStatus.Available, p))).CreateAsync(new(b.BorrowerId, p.LoanProductVersionId, 1, "Build"), default)); }
    [Theory][InlineData(LoanProductVersionLookupStatus.NotFound)][InlineData(LoanProductVersionLookupStatus.Draft)][InlineData(LoanProductVersionLookupStatus.ProductInactive)][InlineData(LoanProductVersionLookupStatus.OutsideEffectivePeriod)] public async Task Unavailable_product_is_rejected(LoanProductVersionLookupStatus status) { var b = Borrower(); await Assert.ThrowsAsync<ProductUnavailableException>(() => new LoanApplicationService(new Store(), new Borrowers(b), new Products(new(status, null))).CreateAsync(new(b.BorrowerId, Guid.NewGuid(), 1, "Build"), default)); }
    sealed class Borrowers(BorrowerContract? value) : IBorrowersModule { public Task<BorrowerContract?> GetAsync(Guid id, CancellationToken ct = default) => Task.FromResult(value); }
    sealed class Products(LoanProductVersionLookup value) : ILoanProductsModule { public Task<LoanProductVersionLookup> GetVersionAsync(Guid id, DateOnly date, CancellationToken ct = default) => Task.FromResult(value); }
    sealed class Store : ILoanApplicationStore { public List<LoanApplication> Values { get; } = []; public Task AddAsync(LoanApplication x, CancellationToken c) { Values.Add(x); return Task.CompletedTask; } public Task<LoanApplication?> FindAsync(Guid id, CancellationToken c) => Task.FromResult(Values.SingleOrDefault(x => x.Id == id)); public Task<LoanApplicationPage> SearchAsync(LoanApplicationSearch s, CancellationToken c) => Task.FromResult(new LoanApplicationPage([], 1, 25, 0)); public void Expect(LoanApplication x, byte[] v) { } public Task SaveAsync(CancellationToken c) => Task.CompletedTask; }
}
