using LoanSystem.Contracts;
using LoanSystem.Modules.LoanOrigination.Application;
using LoanSystem.Modules.LoanOrigination.Domain;
namespace LoanSystem.ApplicationTests;

public sealed class Task10ApplicationServiceTests
{
    [Fact] public async Task Attach_validates_document_actor_and_expected_version() { var app = Prerequisites(); var store = new AppStore(app); var documents = new Documents(true); var service = LoanService(store, documents); var documentId = Guid.NewGuid(); var actor = Guid.NewGuid(); byte[] version = [1]; var result = await service.AttachDocumentAsync(app.Id, documentId, LoanApplicationDocumentType.Ownership, actor, version, default); Assert.NotNull(result); Assert.Equal(documentId, documents.DocumentId); Assert.Equal(actor, documents.Actor); Assert.Same(version, store.Expected); Assert.Single(app.ApplicationDocuments); Assert.True(store.Saved); }
    [Fact] public async Task Attach_rejects_missing_inactive_and_duplicate_documents() { var app = Prerequisites(); var missing = LoanService(new(app), new Documents(false, true)); await Assert.ThrowsAsync<DocumentUnavailableException>(() => missing.AttachDocumentAsync(app.Id, Guid.NewGuid(), LoanApplicationDocumentType.Ownership, Guid.NewGuid(), [1], default)); var inactive = LoanService(new(app), new Documents(false)); await Assert.ThrowsAsync<DocumentUnavailableException>(() => inactive.AttachDocumentAsync(app.Id, Guid.NewGuid(), LoanApplicationDocumentType.Ownership, Guid.NewGuid(), [1], default)); var store = new AppStore(app); var service = LoanService(store, new Documents(true)); var id = Guid.NewGuid(); await service.AttachDocumentAsync(app.Id, id, LoanApplicationDocumentType.Ownership, Guid.NewGuid(), [1], default); await Assert.ThrowsAsync<DocumentAlreadyAttachedException>(() => service.AttachDocumentAsync(app.Id, id, LoanApplicationDocumentType.Ownership, Guid.NewGuid(), [2], default)); }
    [Fact] public async Task Detach_recalculates_readiness_and_unknown_does_not_save() { var app = Prerequisites(); var docs = new Documents(true); var store = new AppStore(app); var service = LoanService(store, docs); foreach (var type in new[] { LoanApplicationDocumentType.Ownership, LoanApplicationDocumentType.Survey, LoanApplicationDocumentType.EngineeringDrawing }) await service.AttachDocumentAsync(app.Id, Guid.NewGuid(), type, Guid.NewGuid(), [1], default); app.CompleteMortgage(Guid.NewGuid()); var id = app.ApplicationDocuments[0].DocumentId; var result = await service.DetachDocumentAsync(app.Id, id, [2], default); Assert.Equal("PrerequisitesPending", result!.Status); Assert.Equal("Pending", result.DocumentPrerequisiteStatus); await Assert.ThrowsAsync<DocumentNotAttachedException>(() => service.DetachDocumentAsync(app.Id, Guid.NewGuid(), [3], default)); var empty = new AppStore(); Assert.Null(await LoanService(empty, docs).DetachDocumentAsync(Guid.NewGuid(), id, [1], default)); Assert.False(empty.Saved); }
    [Fact] public async Task Mortgage_commands_persist_metadata_and_reject_repeat() { var app = Prerequisites(); var store = new AppStore(app); var service = LoanService(store, new Documents(true)); var actor = Guid.NewGuid(); var at = DateTimeOffset.UtcNow; var completed = await service.CompleteMortgageAsync(app.Id, actor, " done ", [1], default); Assert.Equal("Completed", completed!.MortgageStatus); Assert.Equal(actor, completed.MortgageDecision!.ActorUserId); Assert.True(completed.MortgageDecision.DecidedAtUtc >= at); await Assert.ThrowsAsync<MortgageAlreadyDecidedException>(() => service.WaiveMortgageAsync(app.Id, actor, "waive", null, [2], default)); var waivedApp = Prerequisites(); var waived = await LoanService(new(waivedApp), new Documents(true)).WaiveMortgageAsync(waivedApp.Id, actor, " reason ", " comment ", [1], default); Assert.Equal("reason", waived!.MortgageDecision!.Reason); var blank = Prerequisites(); await Assert.ThrowsAsync<MortgageReasonRequiredException>(() => LoanService(new(blank), new Documents(true)).WaiveMortgageAsync(blank.Id, actor, " ", null, [1], default)); }
    [Fact] public async Task Inspection_service_creates_edits_completes_and_propagates_decisions() { var app = CommitteeApproved(); var applications = new AppStore(app); var inspections = new InspectionStore(); var service = new PropertyInspectionService(inspections, applications); byte[] appVersion = [1]; var created = await service.CreateAsync(app.Id, Guid.NewGuid(), appVersion, default); Assert.NotNull(created); Assert.Equal(LoanApplicationStatus.PrerequisitesPending, app.Status); Assert.Same(appVersion, applications.Expected); Assert.Single(await service.ListAsync(app.Id, default)); Assert.NotNull(await service.GetAsync(created.PropertyInspectionId, default)); await Assert.ThrowsAsync<ReinspectionNotSupportedException>(() => service.CreateAsync(app.Id, Guid.NewGuid(), [2], default)); var edit = new EditInspection("Muscat", "Bawshar", "Area", 1, 0, 100, "Good", new(2026, 9, 13), "Suitable", null); var edited = await service.EditAsync(created.PropertyInspectionId, edit, [3], default); var completed = await service.CompleteAsync(created.PropertyInspectionId, Guid.NewGuid(), [4], default); await service.DecideAsync(created.PropertyInspectionId, Guid.NewGuid(), true, null, [5], default); Assert.Equal(InspectionPrerequisiteStatus.Approved, app.InspectionPrerequisiteStatus); Assert.Equal("Muscat", edited!.Governorate); Assert.Equal("Recorded", completed!.Status); Assert.Null(await service.GetAsync(Guid.NewGuid(), default)); }
    private static LoanApplicationService LoanService(AppStore store, IDocumentsModule documents) => new(store, new Borrowers(), new Products(), documents);
    private static LoanApplication Prerequisites() { var app = CommitteeApproved(); app.BeginPrerequisites(); app.MarkInspectionApproved(); return app; }
    private static LoanApplication CommitteeApproved() { var product = Snapshot(); var app = LoanApplication.Create(Guid.NewGuid(), product, 500, "Build", new("C", null, "Name", null, "OM", "MOD", null, null, "Active")); app.EvaluateEligibility(0); app.Submit(); app.ApproveByUnit(Guid.NewGuid()); app.ApproveByCommittee(Guid.NewGuid()); return app; }
    private static ProductSnapshot Snapshot() => new(Guid.NewGuid(), Guid.NewGuid(), "Product", 1, 1000, "OMR", 10, ["Build"], new("OM", 1, [], 240, "Monthly"), DateOnly.MinValue, null, "Active", "Published", DateTimeOffset.UtcNow);
    private sealed class Borrowers : IBorrowersModule { public Task<BorrowerContract?> GetAsync(Guid id, CancellationToken ct = default) => Task.FromResult<BorrowerContract?>(null); }
    private sealed class Products : ILoanProductsModule { public Task<LoanProductVersionLookup> GetVersionAsync(Guid id, DateOnly date, CancellationToken ct = default) => Task.FromResult(new LoanProductVersionLookup(LoanProductVersionLookupStatus.NotFound, null)); }
    private sealed class Documents(bool active, bool missing = false) : IDocumentsModule { public Guid DocumentId { get; private set; } public Guid Actor { get; private set; } public Task<DocumentReferenceContract?> GetAccessibleAsync(Guid id, Guid actor, CancellationToken ct = default) { DocumentId = id; Actor = actor; return Task.FromResult(missing ? null : new DocumentReferenceContract(id, "file", "text/plain", 1, active)); } }
    private sealed class AppStore(params LoanApplication[] values) : ILoanApplicationStore { public List<LoanApplication> Values { get; } = [.. values]; public byte[]? Expected { get; private set; } public bool Saved { get; private set; } public Task AddAsync(LoanApplication value, CancellationToken ct) { Values.Add(value); return Task.CompletedTask; } public Task<LoanApplication?> FindAsync(Guid id, CancellationToken ct) => Task.FromResult(Values.SingleOrDefault(x => x.Id == id)); public Task<LoanApplicationPage> SearchAsync(LoanApplicationSearch search, CancellationToken ct) => Task.FromResult(new LoanApplicationPage([], 1, 25, 0)); public Task<int> CountConflictingApplicationsAsync(Guid borrowerId, Guid excludeApplicationId, CancellationToken ct) => Task.FromResult(0); public void Expect(LoanApplication value, byte[] expected) => Expected = expected; public Task SaveAsync(CancellationToken ct) { Saved = true; return Task.CompletedTask; } }
    private sealed class InspectionStore : IPropertyInspectionStore { public List<PropertyInspection> Values { get; } = []; public byte[]? Expected { get; private set; } public Task AddAsync(PropertyInspection inspection, CancellationToken ct) { Values.Add(inspection); return Task.CompletedTask; } public Task<PropertyInspection?> FindAsync(Guid id, CancellationToken ct) => Task.FromResult(Values.SingleOrDefault(x => x.Id == id)); public Task<IReadOnlyList<PropertyInspection>> FindByApplicationAsync(Guid id, CancellationToken ct) => Task.FromResult<IReadOnlyList<PropertyInspection>>(Values.Where(x => x.LoanApplicationId == id).ToArray()); public void Expect(PropertyInspection inspection, byte[] expected) => Expected = expected; public Task SaveAsync(CancellationToken ct) => Task.CompletedTask; }
}
