import { expect, test } from '@playwright/test';

const crcTable = Array.from({ length: 256 }, (_, n) => { let c = n; for (let k = 0; k < 8; k++) c = (c & 1) ? 0xedb88320 ^ (c >>> 1) : c >>> 1; return c >>> 0; });
const crc32 = (data: Buffer) => { let crc = 0xffffffff; for (const byte of data) crc = crcTable[(crc ^ byte) & 0xff] ^ (crc >>> 8); return (crc ^ 0xffffffff) >>> 0; };
function zip(entries: Record<string, string>) { const files: Buffer[] = []; const directory: Buffer[] = []; let offset = 0; for (const [name, value] of Object.entries(entries)) { const n = Buffer.from(name); const data = Buffer.from(value); const crc = crc32(data); const local = Buffer.alloc(30); local.writeUInt32LE(0x04034b50); local.writeUInt16LE(20, 4); local.writeUInt32LE(crc, 14); local.writeUInt32LE(data.length, 18); local.writeUInt32LE(data.length, 22); local.writeUInt16LE(n.length, 26); files.push(local, n, data); const central = Buffer.alloc(46); central.writeUInt32LE(0x02014b50); central.writeUInt16LE(20, 4); central.writeUInt16LE(20, 6); central.writeUInt32LE(crc, 16); central.writeUInt32LE(data.length, 20); central.writeUInt32LE(data.length, 24); central.writeUInt16LE(n.length, 28); central.writeUInt32LE(offset, 42); directory.push(central, n); offset += local.length + n.length + data.length; } const directoryBuffer = Buffer.concat(directory); const end = Buffer.alloc(22); end.writeUInt32LE(0x06054b50); end.writeUInt16LE(Object.keys(entries).length, 8); end.writeUInt16LE(Object.keys(entries).length, 10); end.writeUInt32LE(directoryBuffer.length, 12); end.writeUInt32LE(offset, 16); return Buffer.concat([...files, directoryBuffer, end]); }
function workbook(rows: string[][]) { const cell = (value: string, column: number, row: number) => `<c r="${String.fromCharCode(65 + column)}${row}" t="inlineStr"><is><t>${value}</t></is></c>`; const values = [['Civil Number', 'Full Name', 'Nationality', 'Organization', 'Employee Number'], ...rows]; const sheet = values.map((row, r) => `<row r="${r + 1}">${row.map((v, c) => cell(v, c, r + 1)).join('')}</row>`).join(''); return zip({ '[Content_Types].xml': '<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>', '_rels/.rels': '<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>', 'xl/workbook.xml': '<?xml version="1.0"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Borrowers" sheetId="1" r:id="rId1"/></sheets></workbook>', 'xl/_rels/workbook.xml.rels': '<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>', 'xl/worksheets/sheet1.xml': `<?xml version="1.0"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>${sheet}</sheetData></worksheet>` }); }

test('TASK-04 validates before explicit import, imports valid rows once, and previews duplicates', async ({ page }) => {
  const username = process.env.E2E_ADMIN_USERNAME; const password = process.env.E2E_ADMIN_PASSWORD; test.skip(!username || !password, 'Disposable credentials must be injected'); const unique = `${Date.now()}${Math.floor(Math.random() * 100000)}`; const civil = `e2e-import-${unique}`; const duplicate = `e2e-duplicate-${unique}`;
  await page.goto('/'); await page.getByLabel('Username').fill(username!); await page.getByLabel('Password').fill(password!); await page.getByRole('button', { name: 'Login' }).click(); await page.getByRole('button', { name: 'Borrower Import' }).click();
  await page.getByLabel('Choose Excel workbook').setInputFiles({ name: 'borrowers.xlsx', mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', buffer: workbook([[civil, `Imported ${unique}`, 'Omani', 'E2E', `employee-${unique}`], [duplicate, 'Duplicate One', 'Omani', 'E2E', ''], [duplicate, 'Duplicate Two', 'Omani', 'E2E', '']]) });
  const validationResponse = page.waitForResponse(r => new URL(r.url()).pathname === '/api/v1/borrower-imports/validate'); await page.getByRole('button', { name: 'Validate' }).click(); const response = await validationResponse; expect(response.status()).toBe(201); const preview = await response.json(); await expect(page.getByText('Duplicate Civil Number in workbook.').first()).toBeVisible(); await expect(page.getByText(/Valid rows:/)).toContainText('1');
  expect(await page.evaluate(async value => (await fetch(`/api/v1/borrowers?civilNumber=${encodeURIComponent(value)}`)).json(), civil)).toMatchObject({ totalCount: 0 });
  await page.getByRole('button', { name: 'Execute Import' }).click(); await expect(page.getByText(/Imported:/)).toContainText('1'); const retry = await page.evaluate(async id => ({ status: (await fetch(`/api/v1/borrower-imports/${id}/execute`, { method: 'POST' })).status }), preview.batchId); expect(retry.status).toBe(200);
  await page.getByRole('button', { name: 'Borrowers' }).click(); await page.getByLabel('Civil Number').fill(civil); await page.getByRole('button', { name: 'Search' }).click(); await expect(page.getByRole('row').filter({ hasText: civil })).toHaveCount(1); expect(await page.evaluate(async value => (await fetch(`/api/v1/borrowers?civilNumber=${encodeURIComponent(value)}`)).json(), civil)).toMatchObject({ totalCount: 1 }); expect(await page.evaluate(async value => (await fetch(`/api/v1/borrowers?civilNumber=${encodeURIComponent(value)}`)).json(), duplicate)).toMatchObject({ totalCount: 0 }); await page.getByRole('button', { name: 'Logout' }).click();
});
