using LoanSystem.Modules.LoanProducts.Application;
using LoanSystem.Modules.LoanProducts.Domain;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;
namespace LoanSystem.Modules.LoanProducts.Presentation;

internal static class LoanProductEndpoints
{
    public static void Map(IEndpointRouteBuilder e) { var g = e.MapGroup("/api/v1/loan-products").WithTags("Loan Products"); g.MapGet("/available", async (LoanProductService s, CancellationToken c) => Results.Ok(await s.AvailableAsync(c))).RequireAuthorization(LoanProductPermissions.Read); g.MapGet("/", async (LoanProductService s, CancellationToken c) => Results.Ok(await s.ListAsync(c))).RequireAuthorization(LoanProductPermissions.Read); g.MapGet("/{id:guid}", Get).RequireAuthorization(LoanProductPermissions.Read); g.MapPost("/", Create).RequireAuthorization(LoanProductPermissions.Manage); g.MapPost("/{id:guid}/versions", Draft).RequireAuthorization(LoanProductPermissions.Manage); g.MapPut("/{id:guid}/versions/{versionId:guid}", Edit).RequireAuthorization(LoanProductPermissions.Manage); g.MapPost("/{id:guid}/versions/{versionId:guid}/publish", Publish).RequireAuthorization(LoanProductPermissions.Publish); g.MapPost("/{id:guid}/activate", (Guid id, HttpRequest r, LoanProductService s, CancellationToken c) => Status(id, true, r, s, c)).RequireAuthorization(LoanProductPermissions.ManageStatus); g.MapPost("/{id:guid}/deactivate", (Guid id, HttpRequest r, LoanProductService s, CancellationToken c) => Status(id, false, r, s, c)).RequireAuthorization(LoanProductPermissions.ManageStatus); }
    static async Task<IResult> Get(Guid id, LoanProductService s, CancellationToken c) { var x = await s.GetAsync(id, c); return x is null ? Problem(404, "Loan product not found", "loanProducts.notFound") : Header(Results.Ok(x), x.ETag); }
    static async Task<IResult> Create(CreateProductInput i, LoanProductService s, CancellationToken c) { try { var x = await s.CreateAsync(i.Name, c); return Header(Results.Created($"/api/v1/loan-products/{x.LoanProductId}", x), x.ETag); } catch (LoanProductValidationException) { return Validation(); } }
    static async Task<IResult> Draft(Guid id, VersionInput i, LoanProductService s, CancellationToken c) { try { var x = await s.CreateDraftAsync(id, i, c); return x is null ? Problem(404, "Loan product not found", "loanProducts.notFound") : Header(Results.Created($"/api/v1/loan-products/{id}/versions/{x.VersionId}", x), x.ETag); } catch (LoanProductValidationException) { return Validation(); } catch (LoanProductVersionConflictException) { return Problem(409, "A version-number conflict occurred", "loanProducts.versionConflict"); } }
    static async Task<IResult> Edit(Guid id, Guid versionId, VersionInput i, HttpRequest r, LoanProductService s, CancellationToken c) { if (!Version(r, out var v)) return Stale(); try { var x = await s.EditAsync(id, versionId, i, v, c); return x is null ? Problem(404, "Version not found", "loanProducts.versionNotFound") : Header(Results.Ok(x), x.ETag); } catch (LoanProductVersionImmutableException) { return Problem(409, "Published versions are immutable", "loanProducts.versionImmutable"); } catch (LoanProductValidationException) { return Validation(); } catch (LoanProductConcurrencyException) { return Stale(); } }
    static async Task<IResult> Publish(Guid id, Guid versionId, LoanProductService s, CancellationToken c) { try { var x = await s.PublishAsync(id, versionId, c); return x is null ? Problem(404, "Version not found", "loanProducts.versionNotFound") : Header(Results.Ok(x), x.ETag); } catch (LoanProductInvalidStateException) { return Problem(409, "Version cannot be published", "loanProducts.invalidState"); } catch (EffectivePeriodConflictException) { return Problem(409, "Effective period overlaps a published version", "loanProducts.effectivePeriodConflict"); } }
    static async Task<IResult> Status(Guid id, bool active, HttpRequest r, LoanProductService s, CancellationToken c) { if (!Version(r, out var v)) return Stale(); try { var x = await s.StatusAsync(id, active, v, c); return x is null ? Problem(404, "Loan product not found", "loanProducts.notFound") : Header(Results.Ok(x), x.ETag); } catch (LoanProductConcurrencyException) { return Stale(); } }
    static bool Version(HttpRequest r, out byte[] v) { v = []; try { if (!r.Headers.TryGetValue("If-Match", out var h)) return false; v = Convert.FromBase64String(h.ToString().Trim('"')); return true; } catch (FormatException) { return false; } }
    static IResult Validation() => Problem(422, "Loan product configuration is invalid", "loanProducts.validation"); static IResult Stale() => Problem(412, "Loan product was changed by another request", "loanProducts.concurrencyConflict"); static IResult Problem(int s, string t, string c) => Results.Problem(statusCode: s, title: t, extensions: new Dictionary<string, object?> { { "errorCode", c } }); static HeaderResult Header(IResult x, string e) => new(x, e); internal sealed record CreateProductInput(string Name); private sealed class HeaderResult(IResult inner, string etag) : IResult { public Task ExecuteAsync(HttpContext c) { c.Response.Headers.ETag = $"\"{etag}\""; return inner.ExecuteAsync(c); } }
}
