using Microsoft.EntityFrameworkCore.Migrations;
using LoanSystem.Modules.LoanProducts.Infrastructure;
using Microsoft.EntityFrameworkCore.Infrastructure;
namespace LoanSystem.Modules.LoanProducts.Infrastructure.Migrations;
[DbContext(typeof(LoanProductsDbContext))]
[Migration("20260827000000_LoanProducts_Initial")]
public sealed class LoanProductsInitial:Migration
{
 protected override void Up(MigrationBuilder m){m.EnsureSchema("loan_products");m.CreateTable("loan_products","loan_products",t=>new{loan_product_id=t.Column<Guid>(),name=t.Column<string>(maxLength:200),status=t.Column<string>(maxLength:20),created_at_utc=t.Column<DateTimeOffset>(),updated_at_utc=t.Column<DateTimeOffset>(),row_version=t.Column<byte[]>(rowVersion:true)},constraints:t=>t.PrimaryKey("PK_loan_products",x=>x.loan_product_id));m.CreateTable("loan_product_versions","loan_products",t=>new{version_id=t.Column<Guid>(),loan_product_id=t.Column<Guid>(),version_number=t.Column<int>(),maximum_amount=t.Column<decimal>(type:"decimal(19,4)"),currency=t.Column<string>(type:"char(3)"),deduction_percentage=t.Column<decimal>(type:"decimal(9,4)"),eligibility_configuration=t.Column<string>(type:"nvarchar(max)"),effective_from=t.Column<DateOnly>(type:"date"),effective_to=t.Column<DateOnly>(type:"date",nullable:true),status=t.Column<string>(maxLength:20),published_at_utc=t.Column<DateTimeOffset>(nullable:true),created_at_utc=t.Column<DateTimeOffset>(),row_version=t.Column<byte[]>(rowVersion:true)},constraints:t=>{t.PrimaryKey("PK_loan_product_versions",x=>x.version_id);t.ForeignKey("FK_versions_products",x=>x.loan_product_id,"loan_products","loan_products","loan_product_id",onDelete:ReferentialAction.Restrict);});m.CreateIndex("IX_versions_product_number","loan_products","loan_product_versions",new[]{"loan_product_id","version_number"},unique:true);m.CreateTable("loan_product_financing_types","loan_products",t=>new{version_id=t.Column<Guid>(),financing_type=t.Column<string>(maxLength:100)},constraints:t=>{t.PrimaryKey("PK_loan_product_financing_types",x=>new{x.version_id,x.financing_type});t.ForeignKey("FK_financing_types_versions",x=>x.version_id,"loan_products","loan_product_versions","version_id",onDelete:ReferentialAction.Cascade);});}
 protected override void Down(MigrationBuilder m){m.DropTable("loan_product_financing_types","loan_products");m.DropTable("loan_product_versions","loan_products");m.DropTable("loan_products","loan_products");}
}
