using LoanSystem.Modules.Borrowers.Application;using LoanSystem.Modules.Borrowers.Domain;using Microsoft.AspNetCore.Builder;using Microsoft.AspNetCore.Http;using Microsoft.AspNetCore.Routing;
namespace LoanSystem.Modules.Borrowers.Presentation;
internal static class BorrowerEndpoints
{
 public static void Map(IEndpointRouteBuilder e){var g=e.MapGroup("/api/v1/borrowers").WithTags("Borrowers");g.MapGet("/",Search).RequireAuthorization(BorrowerPermissions.Read);g.MapGet("/{id:guid}",Get).RequireAuthorization(BorrowerPermissions.Read);g.MapPost("/",Create).RequireAuthorization(BorrowerPermissions.Create);g.MapPut("/{id:guid}",Update).RequireAuthorization(BorrowerPermissions.Update);g.MapPost("/{id:guid}/activate",(Guid id,HttpRequest r,BorrowerService s,CancellationToken c)=>Status(id,true,r,s,c)).RequireAuthorization(BorrowerPermissions.ManageStatus);g.MapPost("/{id:guid}/deactivate",(Guid id,HttpRequest r,BorrowerService s,CancellationToken c)=>Status(id,false,r,s,c)).RequireAuthorization(BorrowerPermissions.ManageStatus);}
 static async Task<IResult>Search(string? civilNumber,string? employeeNumber,string? name,string? organization,BorrowerStatus? status,int pageNumber,int pageSize,BorrowerService s,CancellationToken ct)=>Results.Ok(await s.SearchAsync(new(civilNumber,employeeNumber,name,organization,status,pageNumber==0?1:pageNumber,pageSize==0?25:pageSize),ct));
 static async Task<IResult>Get(Guid id,BorrowerService s,CancellationToken ct){var x=await s.GetAsync(id,ct);return x is null?Problem(404,"Borrower not found","borrowers.notFound"):Ok(x);}
 static async Task<IResult>Create(BorrowerInput input,BorrowerService s,CancellationToken ct){try{var x=await s.RegisterAsync(input,ct);return Header(Results.Created($"/api/v1/borrowers/{x.BorrowerId}",x),x.ETag);}catch(BorrowerValidationException){return Problem(422,"Borrower data is invalid","borrowers.validation");}catch(BorrowerConflictException x){return Problem(409,"Borrower identifier already exists",x.Code);}}
 static async Task<IResult>Update(Guid id,BorrowerInput input,HttpRequest r,BorrowerService s,CancellationToken ct){if(!Version(r,out var v))return Stale();try{var x=await s.UpdateAsync(id,input,v,ct);return x is null?Problem(404,"Borrower not found","borrowers.notFound"):Ok(x);}catch(BorrowerValidationException){return Problem(422,"Borrower data is invalid","borrowers.validation");}catch(BorrowerConflictException x){return Problem(409,"Borrower identifier already exists",x.Code);}catch(BorrowerConcurrencyException){return Stale();}}
 static async Task<IResult>Status(Guid id,bool active,HttpRequest r,BorrowerService s,CancellationToken ct){if(!Version(r,out var v))return Stale();try{var x=await s.StatusAsync(id,active,v,ct);return x is null?Problem(404,"Borrower not found","borrowers.notFound"):Ok(x);}catch(BorrowerConcurrencyException){return Stale();}}
 static bool Version(HttpRequest r,out byte[] v){v=[];try{if(!r.Headers.TryGetValue("If-Match",out var h))return false;v=Convert.FromBase64String(h.ToString().Trim('"'));return true;}catch(FormatException){return false;}}
 static IResult Ok(BorrowerDto x)=>Header(Results.Ok(x),x.ETag);static IResult Header(IResult x,string etag)=>new HeaderResult(x,etag);static IResult Stale()=>Problem(412,"Borrower was changed by another request","borrowers.concurrencyConflict");static IResult Problem(int status,string title,string code)=>Results.Problem(statusCode:status,title:title,extensions:new Dictionary<string,object?>{{"errorCode",code}});
 sealed class HeaderResult(IResult inner,string etag):IResult{public Task ExecuteAsync(HttpContext c){c.Response.Headers.ETag=$"\"{etag}\"";return inner.ExecuteAsync(c);}}
}
