using LoanSystem.Modules.LoanOrigination.Domain;
using LoanSystem.Modules.LoanOrigination.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Testcontainers.MsSql;
namespace LoanSystem.IntegrationTests;

public sealed class LoanOriginationPersistenceTests
{
    [Fact] public async Task Fresh_migration_persists_historical_snapshots_and_rowversion() { if (!File.Exists("/var/run/docker.sock") && string.IsNullOrWhiteSpace(Environment.GetEnvironmentVariable("DOCKER_HOST"))) return; await using var sql = new MsSqlBuilder("mcr.microsoft.com/mssql/server:2022-latest").Build(); await sql.StartAsync(); var options = new DbContextOptionsBuilder<LoanOriginationDbContext>().UseSqlServer(sql.GetConnectionString()).Options; Guid id; byte[] draftVersion; await using (var db = new LoanOriginationDbContext(options)) { await db.Database.MigrateAsync(); var product = new ProductSnapshot(Guid.NewGuid(), Guid.NewGuid(), "Original Product", 1, 100000, "OMR", 10, ["Build"], new("OM", 1, [new("A", 70000)], 240, "Monthly"), new(2026, 1, 1), null, "Active", "Published", DateTimeOffset.UtcNow); var app = LoanApplication.Create(Guid.NewGuid(), product, 50000, "Build", new("C1", "E1", "Original Name", null, "OM", "MOD", "A", "Employment", "Active")); id = app.Id; await db.AddAsync(app); await db.SaveChangesAsync(); draftVersion = app.RowVersion.ToArray(); app.EvaluateEligibility(0); app.Submit(); await db.SaveChangesAsync(); Assert.NotEqual(draftVersion, app.RowVersion); } await using (var fresh = new LoanOriginationDbContext(options)) { var loaded = await fresh.LoanApplications.SingleAsync(x => x.Id == id); Assert.Equal("Original Name", loaded.BorrowerSnapshot.FullName); Assert.Equal("A", loaded.BorrowerSnapshot.RankGrade); Assert.Equal("Original Product", loaded.ProductSnapshot.ProductName); Assert.True(loaded.EligibilityDecision!.IsEligible); Assert.Equal(70000, loaded.EligibilityDecision.PermittedAmount); Assert.Equal(LoanApplicationStatus.Submitted, loaded.Status); Assert.NotNull(loaded.SubmittedAtUtc); var columns = await fresh.Database.SqlQueryRaw<int>("SELECT COUNT(*) AS [Value] FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='loan_origination' AND TABLE_NAME='loan_applications' AND COLUMN_NAME IN ('borrower_snapshot','product_snapshot','eligibility_snapshot') AND DATA_TYPE='nvarchar' AND CHARACTER_MAXIMUM_LENGTH=-1").SingleAsync(); Assert.Equal(3, columns); var submittedColumn = await fresh.Database.SqlQueryRaw<int>("SELECT COUNT(*) AS [Value] FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='loan_origination' AND TABLE_NAME='loan_applications' AND COLUMN_NAME='submitted_at_utc' AND DATA_TYPE='datetimeoffset'").SingleAsync(); Assert.Equal(1, submittedColumn); var foreignKeys = await fresh.Database.SqlQueryRaw<int>("SELECT COUNT(*) AS [Value] FROM sys.foreign_keys WHERE parent_object_id=OBJECT_ID('loan_origination.loan_applications')").SingleAsync(); Assert.Equal(0, foreignKeys); } }
}
