import'../i18n';import{render,screen}from'@testing-library/react';import userEvent from'@testing-library/user-event';import{QueryClient,QueryClientProvider}from'@tanstack/react-query';import{beforeEach,expect,it,vi}from'vitest';import{LoanProductsPage}from'./LoanProductsPage';
const fetchMock=vi.fn();beforeEach(()=>vi.stubGlobal('fetch',fetchMock));const json=(x:unknown)=>Promise.resolve(new Response(JSON.stringify(x),{status:200,headers:{'Content-Type':'application/json'}}));function show(){return render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false},mutations:{retry:false}}})}><LoanProductsPage permissions={['loanProducts.read','loanProducts.manage','loanProducts.publish','loanProducts.manageStatus']}/></QueryClientProvider>)}
it('lists and creates configurable products',async()=>{fetchMock.mockImplementation((u:string,init?:RequestInit)=>u.endsWith('/loan-products')&&init?.method==='POST'?json({}):json([{loanProductId:'p',name:'Housing',status:'Active',versionCount:0}]));show();expect(await screen.findByText('Housing')).toBeInTheDocument();await userEvent.click(screen.getByText('Create Product'));await userEvent.type(screen.getByLabelText('Name'),'New product');await userEvent.click(screen.getByRole('button',{name:'Create'}));expect(fetchMock).toHaveBeenCalledWith('/api/v1/loan-products',expect.objectContaining({method:'POST'}));});
it('shows detail and a typed draft form',async()=>{fetchMock.mockImplementation((u:string)=>u.endsWith('/p')?json({loanProductId:'p',name:'Housing',status:'Active',createdAtUtc:'',eTag:'p',versions:[]}):json([{loanProductId:'p',name:'Housing',status:'Active',versionCount:0}]));show();await userEvent.click(await screen.findByText('Housing'));expect(await screen.findByText('Create Draft Version')).toBeInTheDocument();await userEvent.click(screen.getByText('Create Draft Version'));expect(screen.getByLabelText('Required Nationality')).toBeInTheDocument();expect(screen.getByText('Purchase Existing House ×')).toBeInTheDocument();expect(screen.getByText('Build New House ×')).toBeInTheDocument();});
it('edits and persists multiple typed rank rules, financing types, publish and status',async()=>{
 const version={versionId:'v',versionNumber:1,maximumAmount:10000,currency:'OMR',deductionPercentage:30,financingTypes:['Build'],eligibilityConfiguration:{requiredNationality:'Configured',maximumApplicationCount:2,rankGradeAmountRules:[{rankGrade:'G',maximumAmount:5000}],term:{maximumTermMonths:120,dueDateRule:'Configured'}},effectiveFrom:'2026-01-01',effectiveTo:null,status:'Draft',eTag:'v'};
 fetchMock.mockImplementation(async(u:string,init?:RequestInit)=>{if(init?.method==='PUT'){const body=JSON.parse(String(init.body));version.eligibilityConfiguration.rankGradeAmountRules=body.eligibilityConfiguration.rankGradeAmountRules;return json({...version,...body})}return u.endsWith('/p')?json({loanProductId:'p',name:'Housing',status:'Active',createdAtUtc:'',eTag:'p',versions:[version]}):json([{loanProductId:'p',name:'Housing',status:'Active',versionCount:1}])});
 show();await userEvent.click(await screen.findByText('Housing'));await userEvent.click(await screen.findByText('Edit Draft Version'));
 for(const [label,value]of[['Maximum Amount','9000'],['Currency','USD'],['Deduction Percentage (0–100)','40'],['Required Nationality','N'],['Maximum Application Count','3'],['Maximum Term (months)','60'],['Due-Date Rule','Rule']]as const){const input=screen.getByLabelText(label);await userEvent.clear(input);await userEvent.type(input,value)}
 const firstGrade=screen.getByLabelText('Rank / Grade');await userEvent.clear(firstGrade);await userEvent.type(firstGrade,'R1');const firstAmount=screen.getByLabelText('Rank / Grade Maximum Amount');await userEvent.clear(firstAmount);await userEvent.type(firstAmount,'4000');
 await userEvent.click(screen.getByText('Add Rank / Grade Rule'));const grades=screen.getAllByLabelText('Rank / Grade');const amounts=screen.getAllByLabelText('Rank / Grade Maximum Amount');await userEvent.type(grades[1],'R2');await userEvent.type(amounts[1],'3000');await userEvent.click(screen.getByText('Add Rank / Grade Rule'));await userEvent.click(screen.getAllByText('Remove Rule')[2]);
 await userEvent.click(screen.getByText('Build ×'));const financingField=screen.getAllByRole('group')[0].querySelector('input')!;await userEvent.type(financingField,'Custom');await userEvent.click(screen.getByText('Add'));await userEvent.click(screen.getByText('Save'));
 const updateCall=fetchMock.mock.calls.find(([,init])=>init?.method==='PUT')!;expect(JSON.parse(String(updateCall[1]?.body)).eligibilityConfiguration.rankGradeAmountRules).toEqual([{rankGrade:'R1',maximumAmount:4000},{rankGrade:'R2',maximumAmount:3000}]);expect(await screen.findByText(/R1 — 4000/)).toBeVisible();expect(screen.getByText(/R2 — 3000/)).toBeVisible();await userEvent.click(screen.getByText('Publish'));await userEvent.click(screen.getByText('Deactivate'));
});
